export interface TerritorialWebcam {
  id: string;
  comune: string;
  localita: string;
  provincia: string;
  regione: string;
  lat: number;
  lon: number;
  tipo: 'panoramica' | 'mare' | 'montagna' | 'citta' | 'traffico' | 'vulcano' | 'meteo' | 'porto';
  /** Source: 'static' (default) or 'api' for dynamically fetched webcams */
  source?: 'static' | 'api';
  portale: string;
  url: string;
  attiva: boolean;
}

export const WEBCAMS_ITALIA: TerritorialWebcam[] = [
  // === ROMA - Lazio ===
  {
    id: 'laz-rm-001',
    comune: 'Roma',
    localita: 'Colosseo',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8902,
    lon: 12.4922,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/colosseo.html',
    attiva: true,
  },
  {
    id: 'laz-rm-002',
    comune: 'Roma',
    localita: 'Fontana di Trevi',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.9009,
    lon: 12.4833,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/fontana-di-trevi.html',
    attiva: true,
  },

  {
    id: 'laz-rm-004',
    comune: 'Roma',
    localita: 'Piazza Navona',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8992,
    lon: 12.4731,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/piazza-navona.html',
    attiva: true,
  },
  {
    id: 'laz-rm-005',
    comune: 'Roma',
    localita: 'Pantheon',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8986,
    lon: 12.4769,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/pantheon.html',
    attiva: true,
  },

  // === MILANO - Lombardia (coordinate verificate GPS) ===
  {
    id: 'lom-mi-001',
    comune: 'Milano',
    localita: 'Duomo',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.46421,
    lon: 9.19138,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/duomo-milano.html',
    attiva: true,
  },
  {
    id: 'lom-mi-002',
    comune: 'Milano',
    localita: 'Piazza San Babila',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.46665,
    lon: 9.19742,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/piazza-san-babila.html',
    attiva: true,
  },
  {
    id: 'lom-mi-003',
    comune: 'Milano',
    localita: 'Skyline CityLife - Tre Torri',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.47570,
    lon: 9.15320,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/skyline-milano-city-life.html',
    attiva: true,
  },
  {
    id: 'lom-mi-004',
    comune: 'Milano',
    localita: 'Stadio San Siro',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.47849,
    lon: 9.12215,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/san-siro.html',
    attiva: true,
  },
  {
    id: 'lom-mi-005',
    comune: 'Milano',
    localita: 'Colonne di San Lorenzo',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.45605,
    lon: 9.18320,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/basilica-di-san-lorenzo-maggiore.html',
    attiva: true,
  },
  {
    id: 'lom-mi-006',
    comune: 'Milano',
    localita: 'Scalo Romana - Villaggio Olimpico 2026',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.44650,
    lon: 9.20500,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/milano-scalo-romana.html',
    attiva: true,
  },
  {
    id: 'lom-mi-008',
    comune: 'Milano',
    localita: 'Piazza Duca d\'Aosta - Stazione Centrale',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.48480,
    lon: 9.20300,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/piazza-duca-dsosta.html',
    attiva: true,
  },
  {
    id: 'lom-mi-011',
    comune: 'Milano',
    localita: 'Duomo - Live Camera',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.46421,
    lon: 9.19200,
    tipo: 'citta',
    portale: 'youtube.com',
    url: 'https://www.youtube.com/watch?v=Iuc9BjSriaM',
    attiva: true,
  },
  {
    id: 'lom-mi-012',
    comune: 'Milano',
    localita: 'Skyline Live - Espansione Tv',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.48562,
    lon: 9.19039,
    tipo: 'panoramica',
    portale: 'youtube.com',
    url: 'https://www.youtube.com/watch?v=dsoM6TYIkOI',
    attiva: true,
  },

  // === MILANO AREA METROPOLITANA - Traffico ===
  {
    id: 'lom-mi-t01',
    comune: 'Milano',
    localita: 'Tangenziale Ovest A50 - Ghisolfa',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.49450,
    lon: 9.13200,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/1/ghisolfa',
    attiva: true,
  },
  {
    id: 'lom-mi-t02',
    comune: 'Milano',
    localita: 'Tangenziale Est A51 - Mecenate',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.45600,
    lon: 9.24100,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/2/mecenate',
    attiva: true,
  },
  {
    id: 'lom-mi-t03',
    comune: 'Milano',
    localita: 'Tangenziale Est A51 - Forlanini',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.45200,
    lon: 9.24914,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/2/forlanini-nord',
    attiva: true,
  },
  {
    id: 'lom-mi-t04',
    comune: 'Milano',
    localita: 'Tangenziale Ovest A50 - Muggiano',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.45800,
    lon: 9.12500,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/1/muggiano',
    attiva: true,
  },
  {
    id: 'lom-mi-t05',
    comune: 'Milano',
    localita: 'Tangenziale Ovest A50 - Rozzano',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.38000,
    lon: 9.15000,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/1/rozzano',
    attiva: true,
  },
  {
    id: 'lom-mi-t06',
    comune: 'Milano',
    localita: 'Tangenziale Est A51 - Forlanini Sud',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.44800,
    lon: 9.25200,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/2/forlanini-sud',
    attiva: true,
  },
  {
    id: 'lom-mi-t07',
    comune: 'Sesto San Giovanni',
    localita: 'Tangenziale Nord A52 - Sesto',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.54000,
    lon: 9.23000,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/3/sesto-san-giovanni',
    attiva: true,
  },
  {
    id: 'lom-mi-t08',
    comune: 'Cologno Monzese',
    localita: 'Tangenziale Est A51 - Cologno',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.53000,
    lon: 9.27000,
    tipo: 'traffico',
    portale: 'serravalle.it',
    url: 'https://www.serravalle.it/index.php/pagine/videowall/2/cologno',
    attiva: true,
  },


  // === NAPOLI - Campania ===
  {
    id: 'cam-na-001',
    comune: 'Napoli',
    localita: 'Golfo e Vesuvio',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.8358,
    lon: 14.2488,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/napoli-vesuvio.html',
    attiva: true,
  },
  {
    id: 'cam-na-002',
    comune: 'Napoli',
    localita: 'Lungomare Caracciolo',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.8300,
    lon: 14.2350,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/napoli-maschio-angioino.html',
    attiva: true,
  },
  {
    id: 'cam-na-003',
    comune: 'Napoli',
    localita: 'Vesuvio',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.8210,
    lon: 14.4260,
    tipo: 'vulcano',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/vesuvio.html',
    attiva: true,
  },

  // === FIRENZE - Toscana ===
  {
    id: 'tos-fi-001',
    comune: 'Firenze',
    localita: 'Ponte Vecchio',
    provincia: 'FI',
    regione: 'Toscana',
    lat: 43.7680,
    lon: 11.2531,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/firenze/ponte-vecchio.html',
    attiva: true,
  },
  {
    id: 'tos-fi-002',
    comune: 'Firenze',
    localita: 'Piazza della Signoria',
    provincia: 'FI',
    regione: 'Toscana',
    lat: 43.7696,
    lon: 11.2558,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/firenze/piazza-signoria.html',
    attiva: true,
  },

  // === VENEZIA - Veneto ===
  {
    id: 'ven-ve-001',
    comune: 'Venezia',
    localita: 'Piazza San Marco',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.4343,
    lon: 12.3388,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/piazza-san-marco.html',
    attiva: true,
  },
  {
    id: 'ven-ve-002',
    comune: 'Venezia',
    localita: 'Canal Grande - Rialto',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.4380,
    lon: 12.3358,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/canal-grande-rialto.html',
    attiva: true,
  },

  // === TORINO - Piemonte ===

  // === CALABRIA - Provincia di Cosenza ===
  {
    id: 'cal-cs-001',
    comune: 'Cosenza',
    localita: 'Centro Storico',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3009,
    lon: 16.2539,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/cosenza/cosenza.html',
    attiva: true,
  },
  {
    id: 'cal-cs-003',
    comune: 'Rende',
    localita: 'Università della Calabria',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3566,
    lon: 16.2260,
    tipo: 'citta',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/rende-universita',
    attiva: true,
  },

  {
    id: 'cal-cs-008',
    comune: 'Paola',
    localita: 'Santuario San Francesco',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3608,
    lon: 16.0394,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/paola-santuario',
    attiva: true,
  },

  {
    id: 'cal-cs-012',
    comune: 'Morano Calabro',
    localita: 'Borgo e Pollino',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8419,
    lon: 16.1381,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/morano-calabro-pollino',
    attiva: true,
  },
  {
    id: 'cal-cs-014',
    comune: 'Camigliatello Silano',
    localita: 'Lago Cecita',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3333,
    lon: 16.5250,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/cosenza/camigliatello-silano.html',
    attiva: true,
  },
  {
    id: 'cal-cs-015',
    comune: 'Camigliatello Silano',
    localita: 'Impianti Sci Monte Curcio',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3167,
    lon: 16.5083,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/camigliatello-monte-curcio',
    attiva: false,
  },
  {
    id: 'cal-cs-017',
    comune: 'Longobucco',
    localita: 'Panorama Sila',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.4464,
    lon: 16.6108,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/longobucco-sila',
    attiva: true,
  },

  {
    id: 'cal-cs-021',
    comune: 'Scalea',
    localita: 'Torre Talao',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8100,
    lon: 15.7889,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/scalea-torre-talao',
    attiva: false,
  },

  // === CALABRIA - Provincia di Catanzaro ===
  {
    id: 'cal-cz-001',
    comune: 'Catanzaro',
    localita: 'Piazza Prefettura',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9098,
    lon: 16.5879,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/catanzaro/catanzaro-teatro-politeama.html',
    attiva: true,
  },
  {
    id: 'cal-cz-004',
    comune: 'Lamezia Terme',
    localita: 'Centro Città',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9683,
    lon: 16.3089,
    tipo: 'citta',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/lamezia-terme-centro',
    attiva: true,
  },

  {
    id: 'cal-cz-006',
    comune: 'Soverato',
    localita: 'Spiaggia e Lungomare',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.6872,
    lon: 16.5489,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/catanzaro/spiaggia-soverato.html',
    attiva: true,
  },
  {
    id: 'cal-cz-009',
    comune: 'Taverna',
    localita: 'Centro Storico',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 39.0183,
    lon: 16.5833,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/taverna-centro',
    attiva: true,
  },

  {
    id: 'cal-cz-013',
    comune: 'Botricello',
    localita: 'Spiaggia',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9361,
    lon: 16.8556,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/botricello-spiaggia',
    attiva: true,
  },

  // === CALABRIA - Provincia di Vibo Valentia ===
  {
    id: 'cal-vv-001',
    comune: 'Tropea',
    localita: 'Spiaggia e Santa Maria dell\'Isola',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6769,
    lon: 15.8978,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/vibo-valentia/tropea.html',
    attiva: true,
  },

  {
    id: 'cal-vv-005',
    comune: 'Vibo Marina',
    localita: 'Porto Commerciale',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7083,
    lon: 16.1167,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/vibo-marina-porto',
    attiva: true,
  },
  {
    id: 'cal-vv-006',
    comune: 'Capo Vaticano',
    localita: 'Faro e Costa',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6167,
    lon: 15.8333,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/vibo-valentia/capo-vaticano.html',
    attiva: true,
  },
  {
    id: 'cal-vv-003',
    comune: 'Pizzo Calabro',
    localita: 'Panoramica Costa degli Dei',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7297,
    lon: 16.1597,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/vibo-valentia/panoramica-di-pizzo.html',
    attiva: true,
  },
  {
    id: 'cal-vv-009',
    comune: 'Ricadi',
    localita: 'Santa Domenica',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6250,
    lon: 15.8583,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/ricadi-santa-domenica',
    attiva: true,
  },
  {
    id: 'cal-vv-011',
    comune: 'Filadelfia',
    localita: 'Centro e Panorama',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7167,
    lon: 16.2917,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/filadelfia-panorama',
    attiva: false,
  },

  // === CALABRIA - Provincia di Crotone ===
  {
    id: 'cal-kr-001',
    comune: 'Crotone',
    localita: 'Lungomare e Castello',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0833,
    lon: 17.1236,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/crotone/porto-crotone.html',
    attiva: true,
  },
  {
    id: 'cal-kr-003',
    comune: 'Isola di Capo Rizzuto',
    localita: 'Area Marina Protetta',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 38.9583,
    lon: 17.0917,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/crotone/isola-capo-rizzuto-le-castella.html',
    attiva: true,
  },
  {
    id: 'cal-kr-005',
    comune: 'Cirò Marina',
    localita: 'Porto e Spiaggia',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.3708,
    lon: 17.1250,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/ciro-marina-porto',
    attiva: true,
  },
  {
    id: 'cal-kr-008',
    comune: 'Strongoli',
    localita: 'Strongoli Marina',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.2667,
    lon: 17.0500,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/strongoli-marina',
    attiva: true,
  },
  {
    id: 'cal-kr-010',
    comune: 'Mesoraca',
    localita: 'Panorama Marchesato',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0778,
    lon: 16.7889,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/mesoraca-panorama',
    attiva: false,
  },

  // === CALABRIA - Provincia di Reggio Calabria ===
  {
    id: 'cal-rc-001',
    comune: 'Reggio Calabria',
    localita: 'Lungomare Falcomatà',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1114,
    lon: 15.6472,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/reggio-calabria/reggio-calabria.html',
    attiva: true,
  },
  {
    id: 'cal-rc-002',
    comune: 'Reggio Calabria',
    localita: 'Stretto di Messina',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1097,
    lon: 15.6500,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/reggio-calabria/stretto-messina-reggio-calabria.html',
    attiva: true,
  },
  {
    id: 'cal-rc-004',
    comune: 'Scilla',
    localita: 'Spiaggia di Chianalea',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2528,
    lon: 15.7139,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/calabria/reggio-calabria/scilla-chianalea.html',
    attiva: true,
  },

  {
    id: 'cal-rc-008',
    comune: 'Gioia Tauro',
    localita: 'Porto Commerciale',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.4261,
    lon: 15.8917,
    tipo: 'traffico',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gioia-tauro-porto',
    attiva: true,
  },

  {
    id: 'cal-rc-013',
    comune: 'Gerace',
    localita: 'Borgo Medievale',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2722,
    lon: 16.2194,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gerace-borgo',
    attiva: true,
  },

  {
    id: 'cal-rc-016',
    comune: 'Gambarie',
    localita: 'Piazzale Mangeruca',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1681,
    lon: 15.8444,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gambarie-piazzale',
    attiva: true,
  },

  // === LOMBARDIA ===

  {
    id: 'lom-bs-001',
    comune: 'Brescia',
    localita: 'Piazza della Loggia',
    provincia: 'BS',
    regione: 'Lombardia',
    lat: 45.5416,
    lon: 10.2118,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/brescia/meteo-brescia.html',
    attiva: true,
  },
  {
    id: 'lom-co-001',
    comune: 'Como',
    localita: 'Lago di Como',
    provincia: 'CO',
    regione: 'Lombardia',
    lat: 45.8081,
    lon: 9.0852,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/como/lago-di-como.html',
    attiva: true,
  },
  {
    id: 'lom-lc-001',
    comune: 'Lecco',
    localita: 'Lago di Lecco',
    provincia: 'LC',
    regione: 'Lombardia',
    lat: 45.8556,
    lon: 9.3967,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/lecco/lecco.html',
    attiva: true,
  },

  // === PIEMONTE ===

  // === VENETO ===
  {
    id: 'ven-vr-001',
    comune: 'Verona',
    localita: 'Arena di Verona',
    provincia: 'VR',
    regione: 'Veneto',
    lat: 45.4386,
    lon: 10.9942,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/verona/verona.html',
    attiva: true,
  },
  {
    id: 'ven-pd-001',
    comune: 'Padova',
    localita: 'Piazza delle Erbe',
    provincia: 'PD',
    regione: 'Veneto',
    lat: 45.4075,
    lon: 11.8764,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/padova/arca-sant-antonio-padova.html',
    attiva: true,
  },
  {
    id: 'ven-bl-001',
    comune: 'Cortina d\'Ampezzo',
    localita: 'Centro e Dolomiti',
    provincia: 'BL',
    regione: 'Veneto',
    lat: 46.5369,
    lon: 12.1356,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/belluno/cortina-d-ampezzo-dolomiti.html',
    attiva: true,
  },
  {
    id: 'ven-ve-004',
    comune: 'Jesolo',
    localita: 'Spiaggia Jesolo',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.5078,
    lon: 12.6378,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/jesolo.html',
    attiva: true,
  },

  // === FRIULI VENEZIA GIULIA ===

  // === TRENTINO ALTO ADIGE ===

  {
    id: 'taa-tn-002',
    comune: 'Madonna di Campiglio',
    localita: 'Piste da Sci',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 46.2322,
    lon: 10.8247,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/madonna-di-campiglio.html',
    attiva: true,
  },

  {
    id: 'taa-tn-003',
    comune: 'Canazei',
    localita: 'Dolomiti Fassa',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 46.4764,
    lon: 11.7711,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/canazei.html',
    attiva: true,
  },

  // === LIGURIA ===
  {
    id: 'lig-ge-001',
    comune: 'Genova',
    localita: 'Porto Antico',
    provincia: 'GE',
    regione: 'Liguria',
    lat: 44.4075,
    lon: 8.9278,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/genova/boccadasse-genova.html',
    attiva: true,
  },

  {
    id: 'lig-sp-001',
    comune: 'Riomaggiore',
    localita: 'Cinque Terre',
    provincia: 'SP',
    regione: 'Liguria',
    lat: 44.0997,
    lon: 9.7381,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/la-spezia/riomaggiore.html',
    attiva: true,
  },
  {
    id: 'lig-im-001',
    comune: 'Sanremo',
    localita: 'Porto Vecchio',
    provincia: 'IM',
    regione: 'Liguria',
    lat: 43.8155,
    lon: 7.7764,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/imperia/porto-vecchio-sanremo.html',
    attiva: true,
  },
  {
    id: 'lig-sv-001',
    comune: 'Alassio',
    localita: 'Spiaggia Alassio',
    provincia: 'SV',
    regione: 'Liguria',
    lat: 44.0083,
    lon: 8.1703,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/savona/alassio.html',
    attiva: true,
  },

  // === EMILIA ROMAGNA ===
  {
    id: 'ero-bo-001',
    comune: 'Bologna',
    localita: 'Piazza Maggiore',
    provincia: 'BO',
    regione: 'Emilia Romagna',
    lat: 44.4939,
    lon: 11.3428,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/bologna/bologna-torre-degli-asinelli.html',
    attiva: true,
  },
  {
    id: 'ero-rn-001',
    comune: 'Rimini',
    localita: 'Spiaggia Rimini',
    provincia: 'RN',
    regione: 'Emilia Romagna',
    lat: 44.0678,
    lon: 12.5695,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/rimini/rimini.html',
    attiva: true,
  },
  {
    id: 'ero-rn-002',
    comune: 'Riccione',
    localita: 'Spiaggia Riccione',
    provincia: 'RN',
    regione: 'Emilia Romagna',
    lat: 44.0053,
    lon: 12.6583,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/rimini/riccione.html',
    attiva: true,
  },

  {
    id: 'ero-fc-001',
    comune: 'Cesenatico',
    localita: 'Porto Canale',
    provincia: 'FC',
    regione: 'Emilia Romagna',
    lat: 44.2058,
    lon: 12.3950,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/forli-cesena/cesenatico.html',
    attiva: true,
  },

  // === TOSCANA ===
  {
    id: 'tos-fi-003',
    comune: 'Firenze',
    localita: 'Piazza del Duomo',
    provincia: 'FI',
    regione: 'Toscana',
    lat: 43.7731,
    lon: 11.2560,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/firenze/piazza-duomo-firenze.html',
    attiva: true,
  },
  {
    id: 'tos-pi-001',
    comune: 'Pisa',
    localita: 'Torre di Pisa',
    provincia: 'PI',
    regione: 'Toscana',
    lat: 43.7228,
    lon: 10.3966,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/pisa/pisa.html',
    attiva: true,
  },
  {
    id: 'tos-si-001',
    comune: 'Siena',
    localita: 'Piazza del Campo',
    provincia: 'SI',
    regione: 'Toscana',
    lat: 43.3186,
    lon: 11.3308,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/siena/siena.html',
    attiva: true,
  },

  {
    id: 'tos-lu-002',
    comune: 'Viareggio',
    localita: 'Passeggiata Viareggio',
    provincia: 'LU',
    regione: 'Toscana',
    lat: 43.8678,
    lon: 10.2486,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/lucca/viareggio.html',
    attiva: true,
  },
  {
    id: 'tos-lu-003',
    comune: 'Forte dei Marmi',
    localita: 'Spiaggia Forte dei Marmi',
    provincia: 'LU',
    regione: 'Toscana',
    lat: 43.9631,
    lon: 10.1683,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/lucca/forte-dei-marmi-lungomare.html',
    attiva: true,
  },
  {
    id: 'tos-li-002',
    comune: 'Portoferraio',
    localita: 'Isola d\'Elba',
    provincia: 'LI',
    regione: 'Toscana',
    lat: 42.8139,
    lon: 10.3244,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/isola-elba/isola-d-elba-portoferraio.html',
    attiva: true,
  },

  // === LAZIO (aggiuntive) ===

  {
    id: 'laz-lt-001',
    comune: 'Gaeta',
    localita: 'Lungomare Gaeta',
    provincia: 'LT',
    regione: 'Lazio',
    lat: 41.2119,
    lon: 13.5717,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/latina/gaeta.html',
    attiva: true,
  },

  // === UMBRIA ===

  {
    id: 'umb-pg-002',
    comune: 'Assisi',
    localita: 'Basilica San Francesco',
    provincia: 'PG',
    regione: 'Umbria',
    lat: 43.0694,
    lon: 12.6139,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/perugia/assisi.html',
    attiva: true,
  },

  // === MARCHE ===

  {
    id: 'mar-pu-001',
    comune: 'Pesaro',
    localita: 'Spiaggia Pesaro',
    provincia: 'PU',
    regione: 'Marche',
    lat: 43.9108,
    lon: 12.9139,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/pesaro-urbino/pesaro-baia-flaminia.html',
    attiva: true,
  },

  {
    id: 'mar-an-002',
    comune: 'Senigallia',
    localita: 'Spiaggia Senigallia',
    provincia: 'AN',
    regione: 'Marche',
    lat: 43.7156,
    lon: 13.2194,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/ancona/senigallia.html',
    attiva: true,
  },

  // === ABRUZZO ===
  {
    id: 'abr-pe-001',
    comune: 'Pescara',
    localita: 'Lungomare Pescara',
    provincia: 'PE',
    regione: 'Abruzzo',
    lat: 42.4619,
    lon: 14.2147,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/pescara/spiaggia-pescara.html',
    attiva: true,
  },

  {
    id: 'abr-aq-003',
    comune: 'Scanno',
    localita: 'Lago di Scanno',
    provincia: 'AQ',
    regione: 'Abruzzo',
    lat: 41.9025,
    lon: 13.8803,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://www.meteowebcam.it/webcam/abruzzo/scanno-lago',
    attiva: true,
  },

  // === CAMPANIA (aggiuntive) ===
  {
    id: 'cam-na-004',
    comune: 'Capri',
    localita: 'Faraglioni Capri',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.5509,
    lon: 14.2317,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/capri-skyline.html',
    attiva: true,
  },
  {
    id: 'cam-na-005',
    comune: 'Sorrento',
    localita: 'Porto di Sorrento',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.6263,
    lon: 14.3764,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/sorrento.html',
    attiva: true,
  },
  {
    id: 'cam-sa-001',
    comune: 'Amalfi',
    localita: 'Costiera Amalfitana',
    provincia: 'SA',
    regione: 'Campania',
    lat: 40.6342,
    lon: 14.6027,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/salerno/atrani-costiera-amalfitana.html',
    attiva: true,
  },
  {
    id: 'cam-sa-002',
    comune: 'Positano',
    localita: 'Spiaggia Grande Positano',
    provincia: 'SA',
    regione: 'Campania',
    lat: 40.6281,
    lon: 14.4839,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/salerno/spiaggia-positano.html',
    attiva: true,
  },
  {
    id: 'cam-sa-003',
    comune: 'Salerno',
    localita: 'Lungomare Salerno',
    provincia: 'SA',
    regione: 'Campania',
    lat: 40.6744,
    lon: 14.7611,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/salerno/salerno.html',
    attiva: true,
  },
  {
    id: 'cam-na-006',
    comune: 'Ischia',
    localita: 'Porto Ischia',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.7333,
    lon: 13.9461,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/ischia.html',
    attiva: true,
  },

  // === PUGLIA ===

  {
    id: 'pug-le-002',
    comune: 'Gallipoli',
    localita: 'Spiaggia Gallipoli',
    provincia: 'LE',
    regione: 'Puglia',
    lat: 40.0572,
    lon: 17.9931,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/lecce/gallipoli.html',
    attiva: true,
  },
  {
    id: 'pug-le-003',
    comune: 'Otranto',
    localita: 'Porto Otranto',
    provincia: 'LE',
    regione: 'Puglia',
    lat: 40.1469,
    lon: 18.4942,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/lecce/lungomare-di-otranto.html',
    attiva: true,
  },
  {
    id: 'pug-fg-001',
    comune: 'Vieste',
    localita: 'Gargano Vieste',
    provincia: 'FG',
    regione: 'Puglia',
    lat: 41.8817,
    lon: 16.1778,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/foggia/porto-di-vieste.html',
    attiva: true,
  },
  {
    id: 'pug-ba-002',
    comune: 'Polignano a Mare',
    localita: 'Grotta Palazzese',
    provincia: 'BA',
    regione: 'Puglia',
    lat: 40.9953,
    lon: 17.2189,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/bari/polignano-a-mare.html',
    attiva: true,
  },

  // === BASILICATA ===
  {
    id: 'bas-mt-001',
    comune: 'Matera',
    localita: 'Sassi di Matera',
    provincia: 'MT',
    regione: 'Basilicata',
    lat: 40.6664,
    lon: 16.6043,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/matera/matera.html',
    attiva: true,
  },
  {
    id: 'bas-pz-002',
    comune: 'Maratea',
    localita: 'Costa di Maratea',
    provincia: 'PZ',
    regione: 'Basilicata',
    lat: 39.9972,
    lon: 15.7278,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/potenza/maratea.html',
    attiva: true,
  },

  // === MOLISE ===
  {
    id: 'mol-cb-002',
    comune: 'Termoli',
    localita: 'Borgo Antico Termoli',
    provincia: 'CB',
    regione: 'Molise',
    lat: 42.0006,
    lon: 14.9958,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/campobasso/termoli-borgo-medievale.html',
    attiva: true,
  },

  // === SICILIA ===
  {
    id: 'sic-pa-001',
    comune: 'Palermo',
    localita: 'Piazza Pretoria',
    provincia: 'PA',
    regione: 'Sicilia',
    lat: 38.1157,
    lon: 13.3615,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/palermo/cattedrale-di-palermo.html',
    attiva: true,
  },
  {
    id: 'sic-pa-002',
    comune: 'Palermo',
    localita: 'Porto di Palermo',
    provincia: 'PA',
    regione: 'Sicilia',
    lat: 38.1200,
    lon: 13.3700,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/palermo/porto-palermo.html',
    attiva: true,
  },
  {
    id: 'sic-ct-001',
    comune: 'Catania',
    localita: 'Piazza del Duomo',
    provincia: 'CT',
    regione: 'Sicilia',
    lat: 37.5023,
    lon: 15.0872,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/catania/centro-di-catania.html',
    attiva: true,
  },
  {
    id: 'sic-me-001',
    comune: 'Taormina',
    localita: 'Teatro Greco e Etna',
    provincia: 'ME',
    regione: 'Sicilia',
    lat: 37.8519,
    lon: 15.2922,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/messina/taormina.html',
    attiva: true,
  },

  {
    id: 'sic-pa-003',
    comune: 'Cefalù',
    localita: 'Spiaggia Cefalù',
    provincia: 'PA',
    regione: 'Sicilia',
    lat: 38.0394,
    lon: 14.0219,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/palermo/cefalu-piazza-duomo.html',
    attiva: true,
  },

  {
    id: 'sic-me-002',
    comune: 'Stromboli',
    localita: 'Vulcano Stromboli',
    provincia: 'ME',
    regione: 'Sicilia',
    lat: 38.7931,
    lon: 15.2131,
    tipo: 'vulcano',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/messina/isola-di-stromboli.html',
    attiva: true,
  },
  {
    id: 'sic-me-003',
    comune: 'Lipari',
    localita: 'Isole Eolie',
    provincia: 'ME',
    regione: 'Sicilia',
    lat: 38.4678,
    lon: 14.9556,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/messina/lipari-isole-eolie.html',
    attiva: true,
  },

  // === SARDEGNA ===

  {
    id: 'sar-ss-001',
    comune: 'Alghero',
    localita: 'Centro Storico Alghero',
    provincia: 'SS',
    regione: 'Sardegna',
    lat: 40.5597,
    lon: 8.3197,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/sassari/alghero-baia-tramariglio.html',
    attiva: true,
  },

  {
    id: 'sar-ss-002',
    comune: 'Stintino',
    localita: 'Spiaggia La Pelosa',
    provincia: 'SS',
    regione: 'Sardegna',
    lat: 40.9378,
    lon: 8.2261,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/sassari/stintino.html',
    attiva: true,
  },
  {
    id: 'sar-ot-003',
    comune: 'La Maddalena',
    localita: 'Arcipelago Maddalena',
    provincia: 'OT',
    regione: 'Sardegna',
    lat: 41.2139,
    lon: 9.4058,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/olbia-tempio/la-maddalena.html',
    attiva: true,
  },

  // === VALLE D'AOSTA ===
  {
    id: 'vda-ao-001',
    comune: 'Aosta',
    localita: 'Centro Storico Aosta',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.7372,
    lon: 7.3197,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-daosta/aosta/panorama-di-aosta.html',
    attiva: true,
  },
  {
    id: 'vda-ao-002',
    comune: 'Courmayeur',
    localita: 'Monte Bianco',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.7964,
    lon: 6.9706,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-daosta/aosta/courmayeur-val-ferret.html',
    attiva: true,
  },
  {
    id: 'vda-ao-003',
    comune: 'Cervinia',
    localita: 'Cervino Matterhorn',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.9356,
    lon: 7.6458,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-daosta/aosta/breuil-cervinia-valtournenche.html',
    attiva: true,
  },

  // === MOLISE (aggiunte) ===
  {
    id: 'mol-cb-003',
    comune: 'Termoli',
    localita: 'Litorale di Termoli',
    provincia: 'CB',
    regione: 'Molise',
    lat: 42.0050,
    lon: 14.9900,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/campobasso/litorale-di-termoli.html',
    attiva: true,
  },
  {
    id: 'mol-cb-004',
    comune: 'Campitello Matese',
    localita: 'Piste da Sci',
    provincia: 'CB',
    regione: 'Molise',
    lat: 41.4583,
    lon: 14.3917,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/campobasso/campitello-matese.html',
    attiva: true,
  },
  {
    id: 'mol-cb-005',
    comune: 'Montenero di Bisaccia',
    localita: 'Marina di Montenero',
    provincia: 'CB',
    regione: 'Molise',
    lat: 42.0667,
    lon: 14.7833,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/campobasso/montenero-di-bisaccia.html',
    attiva: true,
  },
  {
    id: 'mol-cb-006',
    comune: 'Campomarino',
    localita: 'Lido di Campomarino',
    provincia: 'CB',
    regione: 'Molise',
    lat: 41.9500,
    lon: 15.0333,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/campobasso/campomarino.html',
    attiva: true,
  },

  // === BASILICATA (aggiunte) ===
  {
    id: 'bas-mt-003',
    comune: 'Craco',
    localita: 'La Citta Fantasma',
    provincia: 'MT',
    regione: 'Basilicata',
    lat: 40.3789,
    lon: 16.4392,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/matera/craco.html',
    attiva: true,
  },
  {
    id: 'bas-pz-003',
    comune: 'Atella',
    localita: 'Panorama di Atella',
    provincia: 'PZ',
    regione: 'Basilicata',
    lat: 40.8681,
    lon: 15.6511,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/potenza/atella.html',
    attiva: true,
  },

  // === ABRUZZO (aggiunte) ===
  {
    id: 'abr-ch-001',
    comune: 'San Salvo',
    localita: 'San Salvo Marina',
    provincia: 'CH',
    regione: 'Abruzzo',
    lat: 42.0489,
    lon: 14.7650,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/chieti/san-salvo-marina.html',
    attiva: true,
  },
  {
    id: 'abr-ch-002',
    comune: 'Rocca San Giovanni',
    localita: 'Costa dei Trabocchi',
    provincia: 'CH',
    regione: 'Abruzzo',
    lat: 42.2431,
    lon: 14.4536,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/chieti/rocca-san-giovanni.html',
    attiva: true,
  },

  // === UMBRIA (aggiunte) ===
  {
    id: 'umb-pg-004',
    comune: 'Castelluccio di Norcia',
    localita: 'Piana di Castelluccio',
    provincia: 'PG',
    regione: 'Umbria',
    lat: 42.8281,
    lon: 13.2058,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/perugia/castelluccio-di-norcia.html',
    attiva: true,
  },
  {
    id: 'umb-pg-005',
    comune: 'Spello',
    localita: 'Terme Francescane',
    provincia: 'PG',
    regione: 'Umbria',
    lat: 42.9847,
    lon: 12.6722,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/perugia/terme-francescane.html',
    attiva: true,
  },

  // === VALLE D'AOSTA (aggiunte) ===
  {
    id: 'vda-ao-005',
    comune: 'Aosta',
    localita: 'Via Aubert',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.7375,
    lon: 7.3200,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-daosta/aosta/via-aubert.html',
    attiva: true,
  },

  // === FRIULI VENEZIA GIULIA (aggiunte) ===
  {
    id: 'fvg-pn-001',
    comune: 'Clauzetto',
    localita: 'Grotte di Pradis',
    provincia: 'PN',
    regione: 'Friuli Venezia Giulia',
    lat: 46.2667,
    lon: 12.9167,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/pordenone/clauzetto-grotte-pradis.html',
    attiva: true,
  },

  // === MARCHE (aggiunte) ===
  {
    id: 'mar-pu-003',
    comune: 'Gabicce Mare',
    localita: 'Marina di Gabicce',
    provincia: 'PU',
    regione: 'Marche',
    lat: 43.9639,
    lon: 12.7575,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/pesaro-urbino/marina-di-gabicce-mare.html',
    attiva: true,
  },

  // ============================================================
  // ESPANSIONE v2 — Nuove webcam per copertura nazionale
  // ============================================================

  // === PIEMONTE ===
  {
    id: 'pie-to-001',
    comune: 'Torino',
    localita: 'Piazza Castello',
    provincia: 'TO',
    regione: 'Piemonte',
    lat: 45.0703,
    lon: 7.6869,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/torino/piazza-castello-torino.html',
    attiva: true,
  },
  {
    id: 'pie-to-002',
    comune: 'Torino',
    localita: 'Mole Antonelliana',
    provincia: 'TO',
    regione: 'Piemonte',
    lat: 45.0693,
    lon: 7.6932,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/torino/mole-antonelliana.html',
    attiva: true,
  },
  {
    id: 'pie-to-003',
    comune: 'Torino',
    localita: 'Panoramica - Monte dei Cappuccini',
    provincia: 'TO',
    regione: 'Piemonte',
    lat: 45.0592,
    lon: 7.6975,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/torino/panorama-torino.html',
    attiva: true,
  },
  {
    id: 'pie-to-004',
    comune: 'Sestriere',
    localita: 'Piste da Sci Via Lattea',
    provincia: 'TO',
    regione: 'Piemonte',
    lat: 44.9564,
    lon: 6.8800,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/torino/sestriere.html',
    attiva: true,
  },
  {
    id: 'pie-to-005',
    comune: 'Bardonecchia',
    localita: 'Panorama Bardonecchia',
    provincia: 'TO',
    regione: 'Piemonte',
    lat: 45.0783,
    lon: 6.7044,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/torino/bardonecchia.html',
    attiva: true,
  },
  {
    id: 'pie-cn-001',
    comune: 'Cuneo',
    localita: 'Piazza Galimberti',
    provincia: 'CN',
    regione: 'Piemonte',
    lat: 44.3903,
    lon: 7.5472,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/cuneo/cuneo.html',
    attiva: true,
  },
  {
    id: 'pie-cn-002',
    comune: 'Limone Piemonte',
    localita: 'Comprensorio Sci',
    provincia: 'CN',
    regione: 'Piemonte',
    lat: 44.2028,
    lon: 7.5750,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/cuneo/limone-piemonte.html',
    attiva: true,
  },
  {
    id: 'pie-vb-001',
    comune: 'Stresa',
    localita: 'Lago Maggiore',
    provincia: 'VB',
    regione: 'Piemonte',
    lat: 45.8844,
    lon: 8.5339,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/verbano-cusio-ossola/stresa-lago-maggiore.html',
    attiva: true,
  },
  {
    id: 'pie-vb-002',
    comune: 'Macugnaga',
    localita: 'Monte Rosa',
    provincia: 'VB',
    regione: 'Piemonte',
    lat: 45.9681,
    lon: 7.9686,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/verbano-cusio-ossola/macugnaga-monte-rosa.html',
    attiva: true,
  },
  {
    id: 'pie-al-001',
    comune: 'Alessandria',
    localita: 'Piazza della Libertà',
    provincia: 'AL',
    regione: 'Piemonte',
    lat: 44.9131,
    lon: 8.6156,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/alessandria/alessandria.html',
    attiva: true,
  },
  {
    id: 'pie-no-001',
    comune: 'Orta San Giulio',
    localita: 'Lago d\'Orta',
    provincia: 'NO',
    regione: 'Piemonte',
    lat: 45.7983,
    lon: 8.4086,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/novara/lago-orta.html',
    attiva: true,
  },
  {
    id: 'pie-at-001',
    comune: 'Asti',
    localita: 'Centro Storico',
    provincia: 'AT',
    regione: 'Piemonte',
    lat: 44.9003,
    lon: 8.2064,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/asti/asti.html',
    attiva: true,
  },

  // === FRIULI VENEZIA GIULIA (espansione) ===
  {
    id: 'fvg-ts-001',
    comune: 'Trieste',
    localita: 'Piazza Unità d\'Italia',
    provincia: 'TS',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6495,
    lon: 13.7668,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/trieste/piazza-unita-d-italia.html',
    attiva: true,
  },
  {
    id: 'fvg-ts-002',
    comune: 'Trieste',
    localita: 'Golfo e Molo Audace',
    provincia: 'TS',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6475,
    lon: 13.7700,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/trieste/molo-audace-trieste.html',
    attiva: true,
  },
  {
    id: 'fvg-ud-001',
    comune: 'Udine',
    localita: 'Piazza Libertà',
    provincia: 'UD',
    regione: 'Friuli Venezia Giulia',
    lat: 46.0625,
    lon: 13.2353,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/udine/piazza-liberta-udine.html',
    attiva: true,
  },
  {
    id: 'fvg-ud-002',
    comune: 'Lignano Sabbiadoro',
    localita: 'Spiaggia Lignano',
    provincia: 'UD',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6914,
    lon: 13.1425,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/udine/lignano-sabbiadoro.html',
    attiva: true,
  },
  {
    id: 'fvg-ud-003',
    comune: 'Tarvisio',
    localita: 'Panorama Alpi Giulie',
    provincia: 'UD',
    regione: 'Friuli Venezia Giulia',
    lat: 46.5056,
    lon: 13.5833,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/udine/tarvisio.html',
    attiva: true,
  },
  {
    id: 'fvg-go-001',
    comune: 'Grado',
    localita: 'Spiaggia di Grado',
    provincia: 'GO',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6783,
    lon: 13.3872,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/gorizia/grado.html',
    attiva: true,
  },
  {
    id: 'fvg-ts-003',
    comune: 'Muggia',
    localita: 'Porto di Muggia',
    provincia: 'TS',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6044,
    lon: 13.7700,
    tipo: 'porto',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/trieste/muggia.html',
    attiva: true,
  },

  // === TRENTINO ALTO ADIGE (espansione) ===
  {
    id: 'taa-tn-001',
    comune: 'Trento',
    localita: 'Piazza Duomo',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 46.0678,
    lon: 11.1211,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/piazza-duomo-trento.html',
    attiva: true,
  },
  {
    id: 'taa-bz-001',
    comune: 'Bolzano',
    localita: 'Piazza Walther',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.4983,
    lon: 11.3548,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/piazza-walther-bolzano.html',
    attiva: true,
  },
  {
    id: 'taa-bz-002',
    comune: 'Merano',
    localita: 'Passeggiata Lungo Passirio',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.6713,
    lon: 11.1622,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/merano.html',
    attiva: true,
  },
  {
    id: 'taa-bz-003',
    comune: 'Ortisei',
    localita: 'Val Gardena',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.5739,
    lon: 11.6722,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/ortisei-val-gardena.html',
    attiva: true,
  },
  {
    id: 'taa-bz-004',
    comune: 'Selva di Val Gardena',
    localita: 'Dolomiti - Sassolungo',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.5558,
    lon: 11.7592,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/selva-val-gardena.html',
    attiva: true,
  },
  {
    id: 'taa-tn-004',
    comune: 'Riva del Garda',
    localita: 'Lago di Garda Nord',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 45.8858,
    lon: 10.8411,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/riva-del-garda.html',
    attiva: true,
  },
  {
    id: 'taa-tn-005',
    comune: 'Moena',
    localita: 'Val di Fassa',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 46.3764,
    lon: 11.6608,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/moena.html',
    attiva: true,
  },
  {
    id: 'taa-bz-005',
    comune: 'Brunico',
    localita: 'Plan de Corones',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.7383,
    lon: 11.9386,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/plan-de-corones.html',
    attiva: true,
  },
  {
    id: 'taa-bz-006',
    comune: 'Bressanone',
    localita: 'Centro Storico',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.7167,
    lon: 11.6558,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/bressanone.html',
    attiva: true,
  },
  {
    id: 'taa-tn-006',
    comune: 'Folgaria',
    localita: 'Altopiano di Folgaria',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 45.9178,
    lon: 11.1703,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/folgaria.html',
    attiva: true,
  },

  // === SARDEGNA (espansione) ===
  {
    id: 'sar-ca-001',
    comune: 'Cagliari',
    localita: 'Porto di Cagliari',
    provincia: 'CA',
    regione: 'Sardegna',
    lat: 39.2107,
    lon: 9.1094,
    tipo: 'porto',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/cagliari/porto-cagliari.html',
    attiva: true,
  },
  {
    id: 'sar-ca-002',
    comune: 'Cagliari',
    localita: 'Spiaggia del Poetto',
    provincia: 'CA',
    regione: 'Sardegna',
    lat: 39.1983,
    lon: 9.1650,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/cagliari/spiaggia-del-poetto.html',
    attiva: true,
  },
  {
    id: 'sar-ca-003',
    comune: 'Villasimius',
    localita: 'Porto Giunco',
    provincia: 'CA',
    regione: 'Sardegna',
    lat: 39.1458,
    lon: 9.5397,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/cagliari/villasimius.html',
    attiva: true,
  },
  {
    id: 'sar-ot-001',
    comune: 'Olbia',
    localita: 'Porto di Olbia',
    provincia: 'OT',
    regione: 'Sardegna',
    lat: 40.9244,
    lon: 9.5031,
    tipo: 'porto',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/olbia-tempio/porto-olbia.html',
    attiva: true,
  },
  {
    id: 'sar-ss-003',
    comune: 'Castelsardo',
    localita: 'Panorama Golfo Asinara',
    provincia: 'SS',
    regione: 'Sardegna',
    lat: 40.9133,
    lon: 8.7131,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/sassari/castelsardo.html',
    attiva: true,
  },
  {
    id: 'sar-or-001',
    comune: 'Bosa',
    localita: 'Borgo Medievale',
    provincia: 'OR',
    regione: 'Sardegna',
    lat: 40.2961,
    lon: 8.5011,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/oristano/bosa.html',
    attiva: true,
  },
  {
    id: 'sar-nu-001',
    comune: 'Cala Gonone',
    localita: 'Golfo di Orosei',
    provincia: 'NU',
    regione: 'Sardegna',
    lat: 40.2831,
    lon: 9.6317,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/nuoro/cala-gonone.html',
    attiva: true,
  },

  // === SICILIA (espansione) ===
  {
    id: 'sic-ct-002',
    comune: 'Catania',
    localita: 'Etna Nord',
    provincia: 'CT',
    regione: 'Sicilia',
    lat: 37.7514,
    lon: 15.0047,
    tipo: 'vulcano',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/catania/vulcano-etna.html',
    attiva: true,
  },
  {
    id: 'sic-sr-001',
    comune: 'Siracusa',
    localita: 'Ortigia',
    provincia: 'SR',
    regione: 'Sicilia',
    lat: 37.0597,
    lon: 15.2928,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/siracusa/ortigia-siracusa.html',
    attiva: true,
  },
  {
    id: 'sic-tp-001',
    comune: 'Trapani',
    localita: 'Isole Egadi',
    provincia: 'TP',
    regione: 'Sicilia',
    lat: 38.0175,
    lon: 12.5144,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/trapani/trapani-isole-egadi.html',
    attiva: true,
  },
  {
    id: 'sic-rg-001',
    comune: 'Marina di Ragusa',
    localita: 'Spiaggia Marina di Ragusa',
    provincia: 'RG',
    regione: 'Sicilia',
    lat: 36.7828,
    lon: 14.5553,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/ragusa/marina-di-ragusa.html',
    attiva: true,
  },
  {
    id: 'sic-ag-001',
    comune: 'San Leone',
    localita: 'Spiaggia Agrigento',
    provincia: 'AG',
    regione: 'Sicilia',
    lat: 37.2478,
    lon: 13.5650,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/agrigento/san-leone-agrigento.html',
    attiva: true,
  },

  // === VENETO (espansione) ===
  {
    id: 'ven-tv-001',
    comune: 'Treviso',
    localita: 'Piazza dei Signori',
    provincia: 'TV',
    regione: 'Veneto',
    lat: 45.6669,
    lon: 12.2444,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/treviso/piazza-dei-signori-treviso.html',
    attiva: true,
  },
  {
    id: 'ven-vi-001',
    comune: 'Vicenza',
    localita: 'Piazza dei Signori',
    provincia: 'VI',
    regione: 'Veneto',
    lat: 45.5475,
    lon: 11.5464,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/vicenza/vicenza-piazza-dei-signori.html',
    attiva: true,
  },
  {
    id: 'ven-ro-001',
    comune: 'Rosolina Mare',
    localita: 'Spiaggia Rosolina',
    provincia: 'RO',
    regione: 'Veneto',
    lat: 45.1072,
    lon: 12.2578,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/rovigo/rosolina-mare.html',
    attiva: true,
  },
  {
    id: 'ven-vr-002',
    comune: 'Peschiera del Garda',
    localita: 'Lago di Garda',
    provincia: 'VR',
    regione: 'Veneto',
    lat: 45.4389,
    lon: 10.6919,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/verona/peschiera-del-garda.html',
    attiva: true,
  },
  {
    id: 'ven-ve-005',
    comune: 'Caorle',
    localita: 'Spiaggia Caorle',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.6017,
    lon: 12.8817,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/caorle.html',
    attiva: true,
  },
  {
    id: 'ven-bl-002',
    comune: 'Belluno',
    localita: 'Panorama Dolomiti Bellunesi',
    provincia: 'BL',
    regione: 'Veneto',
    lat: 46.1417,
    lon: 12.2167,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/belluno/belluno-panorama.html',
    attiva: true,
  },

  // === LAZIO (espansione) ===
  {
    id: 'laz-rm-006',
    comune: 'Roma',
    localita: 'Piazza di Spagna',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.9058,
    lon: 12.4823,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/piazza-di-spagna.html',
    attiva: true,
  },
  {
    id: 'laz-rm-007',
    comune: 'Roma',
    localita: 'Via dei Fori Imperiali',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8925,
    lon: 12.4853,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/fori-imperiali.html',
    attiva: true,
  },
  {
    id: 'laz-rm-008',
    comune: 'Roma',
    localita: 'Basilica di San Pietro',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.9022,
    lon: 12.4539,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/piazza-san-pietro.html',
    attiva: true,
  },
  {
    id: 'laz-vt-001',
    comune: 'Civita di Bagnoregio',
    localita: 'La Città che Muore',
    provincia: 'VT',
    regione: 'Lazio',
    lat: 42.6281,
    lon: 12.1144,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/viterbo/civita-di-bagnoregio.html',
    attiva: true,
  },
  {
    id: 'laz-rm-009',
    comune: 'Fiumicino',
    localita: 'Aeroporto Leonardo da Vinci',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8003,
    lon: 12.2389,
    tipo: 'traffico',
    portale: 'airportwebcams.net',
    url: 'https://airportwebcams.net/fco-rome-fiumicino/',
    attiva: true,
  },

  // === EMILIA ROMAGNA (espansione) ===
  {
    id: 'ero-pr-001',
    comune: 'Parma',
    localita: 'Piazza Garibaldi',
    provincia: 'PR',
    regione: 'Emilia Romagna',
    lat: 44.8015,
    lon: 10.3283,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/parma/parma.html',
    attiva: true,
  },
  {
    id: 'ero-mo-001',
    comune: 'Modena',
    localita: 'Piazza Grande',
    provincia: 'MO',
    regione: 'Emilia Romagna',
    lat: 44.6471,
    lon: 10.9254,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/modena/modena.html',
    attiva: true,
  },
  {
    id: 'ero-ra-001',
    comune: 'Ravenna',
    localita: 'Piazza del Popolo',
    provincia: 'RA',
    regione: 'Emilia Romagna',
    lat: 44.4175,
    lon: 12.1997,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/ravenna/ravenna.html',
    attiva: true,
  },
  {
    id: 'ero-fe-001',
    comune: 'Ferrara',
    localita: 'Castello Estense',
    provincia: 'FE',
    regione: 'Emilia Romagna',
    lat: 44.8378,
    lon: 11.6189,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/ferrara/ferrara-castello-estense.html',
    attiva: true,
  },
  {
    id: 'ero-ra-002',
    comune: 'Cervia',
    localita: 'Spiaggia Cervia',
    provincia: 'RA',
    regione: 'Emilia Romagna',
    lat: 44.2608,
    lon: 12.3483,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/ravenna/cervia-milano-marittima.html',
    attiva: true,
  },
  {
    id: 'ero-pc-001',
    comune: 'Piacenza',
    localita: 'Piazza dei Cavalli',
    provincia: 'PC',
    regione: 'Emilia Romagna',
    lat: 45.0525,
    lon: 9.6928,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/piacenza/piacenza.html',
    attiva: true,
  },

  // === TOSCANA (espansione) ===
  {
    id: 'tos-gr-001',
    comune: 'Monte Argentario',
    localita: 'Porto Santo Stefano',
    provincia: 'GR',
    regione: 'Toscana',
    lat: 42.4383,
    lon: 11.1158,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/grosseto/porto-santo-stefano.html',
    attiva: true,
  },
  {
    id: 'tos-ar-001',
    comune: 'Arezzo',
    localita: 'Piazza Grande',
    provincia: 'AR',
    regione: 'Toscana',
    lat: 43.4633,
    lon: 11.8819,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/arezzo/arezzo.html',
    attiva: true,
  },
  {
    id: 'tos-ms-001',
    comune: 'Massa',
    localita: 'Spiaggia Marina di Massa',
    provincia: 'MS',
    regione: 'Toscana',
    lat: 44.0178,
    lon: 10.0925,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/massa-carrara/marina-di-massa.html',
    attiva: true,
  },

  // === CAMPANIA (espansione) ===
  {
    id: 'cam-na-007',
    comune: 'Procida',
    localita: 'Marina Corricella',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.7594,
    lon: 14.0169,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/procida-marina-corricella.html',
    attiva: true,
  },
  {
    id: 'cam-ce-001',
    comune: 'Caserta',
    localita: 'Reggia di Caserta',
    provincia: 'CE',
    regione: 'Campania',
    lat: 41.0733,
    lon: 14.3267,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/caserta/reggia-di-caserta.html',
    attiva: true,
  },

  // === PUGLIA (espansione) ===
  {
    id: 'pug-ba-001',
    comune: 'Bari',
    localita: 'Lungomare Bari',
    provincia: 'BA',
    regione: 'Puglia',
    lat: 41.1171,
    lon: 16.8719,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/bari/bari-lungomare.html',
    attiva: true,
  },
  {
    id: 'pug-bt-001',
    comune: 'Trani',
    localita: 'Porto di Trani',
    provincia: 'BT',
    regione: 'Puglia',
    lat: 41.2778,
    lon: 16.4178,
    tipo: 'porto',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/barletta-andria-trani/trani-porto.html',
    attiva: true,
  },
  {
    id: 'pug-ta-001',
    comune: 'Taranto',
    localita: 'Ponte Girevole',
    provincia: 'TA',
    regione: 'Puglia',
    lat: 40.4736,
    lon: 17.2331,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/taranto/taranto-ponte-girevole.html',
    attiva: true,
  },
  {
    id: 'pug-br-001',
    comune: 'Ostuni',
    localita: 'La Città Bianca',
    provincia: 'BR',
    regione: 'Puglia',
    lat: 40.7297,
    lon: 17.5769,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/brindisi/ostuni.html',
    attiva: true,
  },

  // === LOMBARDIA (espansione) ===
  {
    id: 'lom-bg-001',
    comune: 'Bergamo',
    localita: 'Piazza Vecchia - Città Alta',
    provincia: 'BG',
    regione: 'Lombardia',
    lat: 45.7036,
    lon: 9.6625,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/bergamo/bergamo-alta.html',
    attiva: true,
  },
  {
    id: 'lom-mn-001',
    comune: 'Mantova',
    localita: 'Piazza Sordello',
    provincia: 'MN',
    regione: 'Lombardia',
    lat: 45.1583,
    lon: 10.7944,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/mantova/mantova.html',
    attiva: true,
  },
  {
    id: 'lom-pv-001',
    comune: 'Pavia',
    localita: 'Ponte Coperto',
    provincia: 'PV',
    regione: 'Lombardia',
    lat: 45.1847,
    lon: 9.1581,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/pavia/pavia.html',
    attiva: true,
  },
  {
    id: 'lom-bs-002',
    comune: 'Sirmione',
    localita: 'Lago di Garda',
    provincia: 'BS',
    regione: 'Lombardia',
    lat: 45.4958,
    lon: 10.6069,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/brescia/sirmione-lago-garda.html',
    attiva: true,
  },

  // === LIGURIA (espansione) ===
  {
    id: 'lig-ge-002',
    comune: 'Genova',
    localita: 'Panorama Lanterna',
    provincia: 'GE',
    regione: 'Liguria',
    lat: 44.4047,
    lon: 8.9036,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/genova/genova-lanterna.html',
    attiva: true,
  },
  {
    id: 'lig-sp-002',
    comune: 'Portovenere',
    localita: 'Isola Palmaria',
    provincia: 'SP',
    regione: 'Liguria',
    lat: 44.0531,
    lon: 9.8372,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/la-spezia/portovenere.html',
    attiva: true,
  },
  {
    id: 'lig-sv-002',
    comune: 'Finale Ligure',
    localita: 'Spiaggia Finale',
    provincia: 'SV',
    regione: 'Liguria',
    lat: 44.1689,
    lon: 8.3417,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/savona/finale-ligure.html',
    attiva: true,
  },
  {
    id: 'lig-im-002',
    comune: 'Bordighera',
    localita: 'Lungomare Argentina',
    provincia: 'IM',
    regione: 'Liguria',
    lat: 43.7803,
    lon: 7.6678,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/imperia/bordighera.html',
    attiva: true,
  },

  // === ABRUZZO (espansione) ===
  {
    id: 'abr-aq-001',
    comune: 'L\'Aquila',
    localita: 'Piazza del Duomo',
    provincia: 'AQ',
    regione: 'Abruzzo',
    lat: 42.3505,
    lon: 13.3995,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/l-aquila/l-aquila.html',
    attiva: true,
  },
  {
    id: 'abr-aq-002',
    comune: 'Roccaraso',
    localita: 'Comprensorio Aremogna',
    provincia: 'AQ',
    regione: 'Abruzzo',
    lat: 41.8486,
    lon: 14.0792,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/l-aquila/roccaraso.html',
    attiva: true,
  },
  {
    id: 'abr-te-001',
    comune: 'Giulianova',
    localita: 'Spiaggia Giulianova',
    provincia: 'TE',
    regione: 'Abruzzo',
    lat: 42.7522,
    lon: 13.9594,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/teramo/giulianova.html',
    attiva: true,
  },

  // === MARCHE (espansione) ===
  {
    id: 'mar-an-001',
    comune: 'Ancona',
    localita: 'Porto di Ancona',
    provincia: 'AN',
    regione: 'Marche',
    lat: 43.6158,
    lon: 13.5036,
    tipo: 'porto',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/ancona/porto-ancona.html',
    attiva: true,
  },
  {
    id: 'mar-ap-001',
    comune: 'San Benedetto del Tronto',
    localita: 'Riviera delle Palme',
    provincia: 'AP',
    regione: 'Marche',
    lat: 42.9347,
    lon: 13.8889,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/ascoli-piceno/san-benedetto-del-tronto.html',
    attiva: true,
  },
  {
    id: 'mar-mc-001',
    comune: 'Civitanova Marche',
    localita: 'Spiaggia Civitanova',
    provincia: 'MC',
    regione: 'Marche',
    lat: 43.3050,
    lon: 13.7261,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/macerata/civitanova-marche.html',
    attiva: true,
  },

  // === UMBRIA (espansione) ===
  {
    id: 'umb-pg-001',
    comune: 'Perugia',
    localita: 'Corso Vannucci',
    provincia: 'PG',
    regione: 'Umbria',
    lat: 43.1107,
    lon: 12.3908,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/perugia/perugia-corso-vannucci.html',
    attiva: true,
  },
  {
    id: 'umb-tr-001',
    comune: 'Orvieto',
    localita: 'Duomo di Orvieto',
    provincia: 'TR',
    regione: 'Umbria',
    lat: 42.7181,
    lon: 12.1117,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/terni/orvieto.html',
    attiva: true,
  },
  {
    id: 'umb-tr-002',
    comune: 'Terni',
    localita: 'Cascata delle Marmore',
    provincia: 'TR',
    regione: 'Umbria',
    lat: 42.5522,
    lon: 12.7153,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/terni/cascata-delle-marmore.html',
    attiva: true,
  },

  // === BASILICATA (espansione) ===
  {
    id: 'bas-mt-002',
    comune: 'Policoro',
    localita: 'Spiaggia Policoro',
    provincia: 'MT',
    regione: 'Basilicata',
    lat: 40.2078,
    lon: 16.6750,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/matera/policoro.html',
    attiva: true,
  },
  {
    id: 'bas-pz-001',
    comune: 'Potenza',
    localita: 'Panorama Potenza',
    provincia: 'PZ',
    regione: 'Basilicata',
    lat: 40.6406,
    lon: 15.8033,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/potenza/potenza.html',
    attiva: true,
  },

  // === MOLISE (espansione) ===
  {
    id: 'mol-cb-001',
    comune: 'Campobasso',
    localita: 'Centro Storico',
    provincia: 'CB',
    regione: 'Molise',
    lat: 41.5608,
    lon: 14.6600,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/campobasso/campobasso.html',
    attiva: true,
  },
  {
    id: 'mol-is-001',
    comune: 'Isernia',
    localita: 'Centro Storico',
    provincia: 'IS',
    regione: 'Molise',
    lat: 41.5939,
    lon: 14.2328,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/isernia/isernia.html',
    attiva: true,
  },

  // === VALLE D'AOSTA (espansione) ===
  {
    id: 'vda-ao-004',
    comune: 'La Thuile',
    localita: 'Comprensorio Sci',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.7167,
    lon: 6.9500,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-daosta/aosta/la-thuile.html',
    attiva: true,
  },
  {
    id: 'vda-ao-006',
    comune: 'Gressoney-La-Trinité',
    localita: 'Monte Rosa Ski',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.8342,
    lon: 7.8236,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-daosta/aosta/gressoney.html',
    attiva: true,
  },
];
