export interface TerritorialWebcam {
  id: string;
  comune: string;
  localita: string;
  provincia: string;
  regione: string;
  lat: number;
  lon: number;
  tipo: 'panoramica' | 'mare' | 'montagna' | 'citta' | 'traffico' | 'vulcano';
  portale: string;
  url: string;
  attiva: boolean;
}

export const WEBCAMS_ITALIA: TerritorialWebcam[] = [
  // === ROMA - Lazio ===
  {
    id: 'laz-rm-001',
    comune: 'Roma',
    localita: 'Colosseo',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8902,
    lon: 12.4922,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/colosseo.html',
    attiva: true,
  },
  {
    id: 'laz-rm-002',
    comune: 'Roma',
    localita: 'Fontana di Trevi',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.9009,
    lon: 12.4833,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/fontana-di-trevi.html',
    attiva: true,
  },
  {
    id: 'laz-rm-003',
    comune: 'Roma',
    localita: 'Piazza di Spagna',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.9058,
    lon: 12.4823,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/piazza-di-spagna-roma.html',
    attiva: true,
  },
  {
    id: 'laz-rm-004',
    comune: 'Roma',
    localita: 'Piazza Navona',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8992,
    lon: 12.4731,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/piazza-navona.html',
    attiva: true,
  },
  {
    id: 'laz-rm-005',
    comune: 'Roma',
    localita: 'Pantheon',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8986,
    lon: 12.4769,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/pantheon.html',
    attiva: true,
  },

  // === MILANO - Lombardia ===
  {
    id: 'lom-mi-001',
    comune: 'Milano',
    localita: 'Duomo',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.4642,
    lon: 9.1900,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/duomo-milano.html',
    attiva: true,
  },
  {
    id: 'lom-mi-002',
    comune: 'Milano',
    localita: 'Navigli',
    provincia: 'MI',
    regione: 'Lombardia',
    lat: 45.4500,
    lon: 9.1700,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/milano/navigli-milano.html',
    attiva: true,
  },

  // === NAPOLI - Campania ===
  {
    id: 'cam-na-001',
    comune: 'Napoli',
    localita: 'Golfo e Vesuvio',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.8358,
    lon: 14.2488,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/napoli-golfo.html',
    attiva: true,
  },
  {
    id: 'cam-na-002',
    comune: 'Napoli',
    localita: 'Lungomare Caracciolo',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.8300,
    lon: 14.2350,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/lungomare-napoli.html',
    attiva: true,
  },
  {
    id: 'cam-na-003',
    comune: 'Napoli',
    localita: 'Vesuvio',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.8210,
    lon: 14.4260,
    tipo: 'vulcano',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/vesuvio.html',
    attiva: true,
  },

  // === FIRENZE - Toscana ===
  {
    id: 'tos-fi-001',
    comune: 'Firenze',
    localita: 'Ponte Vecchio',
    provincia: 'FI',
    regione: 'Toscana',
    lat: 43.7680,
    lon: 11.2531,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/firenze/ponte-vecchio.html',
    attiva: true,
  },
  {
    id: 'tos-fi-002',
    comune: 'Firenze',
    localita: 'Piazza della Signoria',
    provincia: 'FI',
    regione: 'Toscana',
    lat: 43.7696,
    lon: 11.2558,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/firenze/piazza-signoria.html',
    attiva: true,
  },

  // === VENEZIA - Veneto ===
  {
    id: 'ven-ve-001',
    comune: 'Venezia',
    localita: 'Piazza San Marco',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.4343,
    lon: 12.3388,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/piazza-san-marco.html',
    attiva: true,
  },
  {
    id: 'ven-ve-002',
    comune: 'Venezia',
    localita: 'Canal Grande - Rialto',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.4380,
    lon: 12.3358,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/rialto.html',
    attiva: true,
  },
  {
    id: 'ven-ve-003',
    comune: 'Venezia',
    localita: 'Bacino San Marco',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.4310,
    lon: 12.3420,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/bacino-san-marco.html',
    attiva: true,
  },

  // === TORINO - Piemonte ===
  {
    id: 'pie-to-001',
    comune: 'Torino',
    localita: 'Piazza Castello',
    provincia: 'TO',
    regione: 'Piemonte',
    lat: 45.0703,
    lon: 7.6869,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/torino/piazza-castello-torino.html',
    attiva: true,
  },
  {
    id: 'pie-to-002',
    comune: 'Torino',
    localita: 'Mole Antonelliana',
    provincia: 'TO',
    regione: 'Piemonte',
    lat: 45.0690,
    lon: 7.6932,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/torino/mole-antonelliana.html',
    attiva: true,
  },

  // === CALABRIA - Provincia di Cosenza ===
  {
    id: 'cal-cs-001',
    comune: 'Cosenza',
    localita: 'Centro Storico',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3009,
    lon: 16.2539,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/cosenza-centro-storico',
    attiva: true,
  },
  {
    id: 'cal-cs-002',
    comune: 'Cosenza',
    localita: 'Ponte Calatrava',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.2975,
    lon: 16.2520,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/cosenza-ponte-calatrava',
    attiva: true,
  },
  {
    id: 'cal-cs-003',
    comune: 'Rende',
    localita: 'Università della Calabria',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3566,
    lon: 16.2260,
    tipo: 'citta',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/rende-universita',
    attiva: true,
  },
  {
    id: 'cal-cs-004',
    comune: 'Scalea',
    localita: 'Lungomare',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8134,
    lon: 15.7917,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/scalea-lungomare',
    attiva: true,
  },
  {
    id: 'cal-cs-005',
    comune: 'Diamante',
    localita: 'Spiaggia e Isola di Cirella',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.6764,
    lon: 15.8197,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/diamante-cirella',
    attiva: false,
  },
  {
    id: 'cal-cs-006',
    comune: 'Praia a Mare',
    localita: 'Isola di Dino',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8950,
    lon: 15.7739,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/praia-a-mare-isola-dino',
    attiva: true,
  },
  {
    id: 'cal-cs-007',
    comune: 'Cetraro',
    localita: 'Porto',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.5167,
    lon: 15.9375,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/cetraro-porto',
    attiva: true,
  },
  {
    id: 'cal-cs-008',
    comune: 'Paola',
    localita: 'Santuario San Francesco',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3608,
    lon: 16.0394,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/paola-santuario',
    attiva: true,
  },
  {
    id: 'cal-cs-009',
    comune: 'Amantea',
    localita: 'Spiaggia',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.1356,
    lon: 16.0717,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/amantea-spiaggia',
    attiva: false,
  },
  {
    id: 'cal-cs-010',
    comune: 'Belvedere Marittimo',
    localita: 'Centro e Mare',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.6167,
    lon: 15.8597,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/belvedere-marittimo',
    attiva: true,
  },
  {
    id: 'cal-cs-011',
    comune: 'Castrovillari',
    localita: 'Piazza Municipio',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8121,
    lon: 16.2028,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/castrovillari-centro',
    attiva: true,
  },
  {
    id: 'cal-cs-012',
    comune: 'Morano Calabro',
    localita: 'Borgo e Pollino',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8419,
    lon: 16.1381,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/morano-calabro-pollino',
    attiva: true,
  },
  {
    id: 'cal-cs-013',
    comune: 'San Giovanni in Fiore',
    localita: 'Abbazia Florense',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.2583,
    lon: 16.6972,
    tipo: 'montagna',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/san-giovanni-in-fiore',
    attiva: false,
  },
  {
    id: 'cal-cs-014',
    comune: 'Camigliatello Silano',
    localita: 'Lago Cecita',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3333,
    lon: 16.5250,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/camigliatello-lago-cecita',
    attiva: true,
  },
  {
    id: 'cal-cs-015',
    comune: 'Camigliatello Silano',
    localita: 'Impianti Sci Monte Curcio',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3167,
    lon: 16.5083,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/camigliatello-monte-curcio',
    attiva: false,
  },
  {
    id: 'cal-cs-016',
    comune: 'Lorica',
    localita: 'Lago Arvo',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.2833,
    lon: 16.5167,
    tipo: 'montagna',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/lorica-lago-arvo',
    attiva: false,
  },
  {
    id: 'cal-cs-017',
    comune: 'Longobucco',
    localita: 'Panorama Sila',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.4464,
    lon: 16.6108,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/longobucco-sila',
    attiva: true,
  },
  {
    id: 'cal-cs-018',
    comune: 'Rossano',
    localita: 'Lungomare Lido Sant\'Angelo',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.5764,
    lon: 16.6367,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/rossano-lido',
    attiva: true,
  },
  {
    id: 'cal-cs-019',
    comune: 'Corigliano Calabro',
    localita: 'Porto e Castello',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.5972,
    lon: 16.5186,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/corigliano-calabro-porto',
    attiva: true,
  },
  {
    id: 'cal-cs-020',
    comune: 'Trebisacce',
    localita: 'Lungomare',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8675,
    lon: 16.5353,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/trebisacce-lungomare',
    attiva: false,
  },
  {
    id: 'cal-cs-021',
    comune: 'Scalea',
    localita: 'Torre Talao',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8100,
    lon: 15.7889,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/scalea-torre-talao',
    attiva: false,
  },

  // === CALABRIA - Provincia di Catanzaro ===
  {
    id: 'cal-cz-001',
    comune: 'Catanzaro',
    localita: 'Piazza Prefettura',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9098,
    lon: 16.5879,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/catanzaro-piazza-prefettura',
    attiva: true,
  },
  {
    id: 'cal-cz-002',
    comune: 'Catanzaro',
    localita: 'Ponte Bisantis',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.8992,
    lon: 16.5750,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/catanzaro-ponte-bisantis',
    attiva: true,
  },
  {
    id: 'cal-cz-003',
    comune: 'Catanzaro Lido',
    localita: 'Lungomare',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.8333,
    lon: 16.6028,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/catanzaro-lido-lungomare',
    attiva: false,
  },
  {
    id: 'cal-cz-004',
    comune: 'Lamezia Terme',
    localita: 'Centro Città',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9683,
    lon: 16.3089,
    tipo: 'citta',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/lamezia-terme-centro',
    attiva: true,
  },
  {
    id: 'cal-cz-005',
    comune: 'Lamezia Terme',
    localita: 'Aeroporto Internazionale',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9058,
    lon: 16.2425,
    tipo: 'traffico',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/lamezia-aeroporto',
    attiva: true,
  },
  {
    id: 'cal-cz-006',
    comune: 'Soverato',
    localita: 'Spiaggia e Lungomare',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.6872,
    lon: 16.5489,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/soverato-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-cz-007',
    comune: 'Soverato',
    localita: 'Porto',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.6908,
    lon: 16.5517,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/soverato-porto',
    attiva: false,
  },
  {
    id: 'cal-cz-008',
    comune: 'Squillace',
    localita: 'Borgo e Golfo',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.7833,
    lon: 16.5194,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/squillace-golfo',
    attiva: false,
  },
  {
    id: 'cal-cz-009',
    comune: 'Taverna',
    localita: 'Centro Storico',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 39.0183,
    lon: 16.5833,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/taverna-centro',
    attiva: true,
  },
  {
    id: 'cal-cz-010',
    comune: 'Tiriolo',
    localita: 'Panorama Istmo',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9417,
    lon: 16.5111,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/tiriolo-panorama',
    attiva: true,
  },
  {
    id: 'cal-cz-011',
    comune: 'Sellia Marina',
    localita: 'Lido',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9056,
    lon: 16.7403,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/sellia-marina-lido',
    attiva: false,
  },
  {
    id: 'cal-cz-012',
    comune: 'Cropani',
    localita: 'Cropani Marina',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9408,
    lon: 16.7778,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/cropani-marina',
    attiva: true,
  },
  {
    id: 'cal-cz-013',
    comune: 'Botricello',
    localita: 'Spiaggia',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9361,
    lon: 16.8556,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/botricello-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-cz-014',
    comune: 'Catanzaro',
    localita: 'Parco della Biodiversità',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9042,
    lon: 16.5944,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/catanzaro-parco-biodiversita',
    attiva: false,
  },
  {
    id: 'cal-cz-015',
    comune: 'Lamezia Terme',
    localita: 'Stazione Centrale',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9639,
    lon: 16.3125,
    tipo: 'traffico',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/lamezia-stazione',
    attiva: false,
  },

  // === CALABRIA - Provincia di Vibo Valentia ===
  {
    id: 'cal-vv-001',
    comune: 'Tropea',
    localita: 'Spiaggia e Santa Maria dell\'Isola',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6769,
    lon: 15.8978,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/tropea-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-vv-002',
    comune: 'Tropea',
    localita: 'Centro Storico e Affaccio',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6792,
    lon: 15.8953,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/tropea-centro-storico',
    attiva: true,
  },
  {
    id: 'cal-vv-003',
    comune: 'Pizzo Calabro',
    localita: 'Castello Murat e Mare',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7297,
    lon: 16.1597,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/pizzo-calabro-castello',
    attiva: true,
  },
  {
    id: 'cal-vv-004',
    comune: 'Pizzo Calabro',
    localita: 'Marina e Porto',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7264,
    lon: 16.1583,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/pizzo-calabro-marina',
    attiva: false,
  },
  {
    id: 'cal-vv-005',
    comune: 'Vibo Marina',
    localita: 'Porto Commerciale',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7083,
    lon: 16.1167,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/vibo-marina-porto',
    attiva: true,
  },
  {
    id: 'cal-vv-006',
    comune: 'Capo Vaticano',
    localita: 'Faro e Costa',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6167,
    lon: 15.8333,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/capo-vaticano-faro',
    attiva: true,
  },
  {
    id: 'cal-vv-007',
    comune: 'Zambrone',
    localita: 'Spiaggia Paradiso del Sub',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6972,
    lon: 15.9861,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/zambrone-spiaggia',
    attiva: false,
  },
  {
    id: 'cal-vv-008',
    comune: 'Briatico',
    localita: 'Lido e Torre',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7306,
    lon: 16.0306,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/briatico-lido',
    attiva: true,
  },
  {
    id: 'cal-vv-009',
    comune: 'Ricadi',
    localita: 'Santa Domenica',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6250,
    lon: 15.8583,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/ricadi-santa-domenica',
    attiva: true,
  },
  {
    id: 'cal-vv-010',
    comune: 'Serra San Bruno',
    localita: 'Certosa',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.5750,
    lon: 16.3264,
    tipo: 'montagna',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/serra-san-bruno-certosa',
    attiva: false,
  },
  {
    id: 'cal-vv-011',
    comune: 'Filadelfia',
    localita: 'Centro e Panorama',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7167,
    lon: 16.2917,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/filadelfia-panorama',
    attiva: false,
  },
  {
    id: 'cal-vv-012',
    comune: 'Joppolo',
    localita: 'Costa e Coccorino',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.5861,
    lon: 15.8972,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/joppolo-coccorino',
    attiva: true,
  },

  // === CALABRIA - Provincia di Crotone ===
  {
    id: 'cal-kr-001',
    comune: 'Crotone',
    localita: 'Lungomare e Castello',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0833,
    lon: 17.1236,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/crotone-lungomare',
    attiva: true,
  },
  {
    id: 'cal-kr-002',
    comune: 'Crotone',
    localita: 'Porto Vecchio',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0806,
    lon: 17.1278,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/crotone-porto-vecchio',
    attiva: true,
  },
  {
    id: 'cal-kr-003',
    comune: 'Isola di Capo Rizzuto',
    localita: 'Area Marina Protetta',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 38.9583,
    lon: 17.0917,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/isola-capo-rizzuto-marina',
    attiva: true,
  },
  {
    id: 'cal-kr-004',
    comune: 'Le Castella',
    localita: 'Fortezza Aragonese',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 38.9083,
    lon: 17.0222,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/le-castella-fortezza',
    attiva: false,
  },
  {
    id: 'cal-kr-005',
    comune: 'Cirò Marina',
    localita: 'Porto e Spiaggia',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.3708,
    lon: 17.1250,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/ciro-marina-porto',
    attiva: true,
  },
  {
    id: 'cal-kr-006',
    comune: 'Cirò Marina',
    localita: 'Punta Alice',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.3833,
    lon: 17.1500,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/ciro-marina-punta-alice',
    attiva: false,
  },
  {
    id: 'cal-kr-007',
    comune: 'Melissa',
    localita: 'Torre Melissa Lido',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.3167,
    lon: 17.0750,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/melissa-lido',
    attiva: true,
  },
  {
    id: 'cal-kr-008',
    comune: 'Strongoli',
    localita: 'Strongoli Marina',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.2667,
    lon: 17.0500,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/strongoli-marina',
    attiva: true,
  },
  {
    id: 'cal-kr-009',
    comune: 'Cutro',
    localita: 'Steccato di Cutro Spiaggia',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 38.9917,
    lon: 17.0167,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/cutro-steccato-spiaggia',
    attiva: false,
  },
  {
    id: 'cal-kr-010',
    comune: 'Mesoraca',
    localita: 'Panorama Marchesato',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0778,
    lon: 16.7889,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/mesoraca-panorama',
    attiva: true,
  },

  // === CALABRIA - Provincia di Reggio Calabria ===
  {
    id: 'cal-rc-001',
    comune: 'Reggio Calabria',
    localita: 'Lungomare Falcomatà',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1114,
    lon: 15.6472,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/reggio-calabria-lungomare',
    attiva: true,
  },
  {
    id: 'cal-rc-002',
    comune: 'Reggio Calabria',
    localita: 'Stretto di Messina',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1097,
    lon: 15.6500,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/reggio-calabria-stretto',
    attiva: true,
  },
  {
    id: 'cal-rc-003',
    comune: 'Reggio Calabria',
    localita: 'Piazza Duomo',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1100,
    lon: 15.6433,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/reggio-calabria-piazza-duomo',
    attiva: true,
  },
  {
    id: 'cal-rc-004',
    comune: 'Scilla',
    localita: 'Spiaggia di Chianalea',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2528,
    lon: 15.7139,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/scilla-chianalea',
    attiva: true,
  },
  {
    id: 'cal-rc-005',
    comune: 'Scilla',
    localita: 'Castello Ruffo e Stretto',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2536,
    lon: 15.7167,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/scilla-castello-ruffo',
    attiva: false,
  },
  {
    id: 'cal-rc-006',
    comune: 'Bagnara Calabra',
    localita: 'Marina e Costa Viola',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2833,
    lon: 15.8083,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/bagnara-calabra-marina',
    attiva: true,
  },
  {
    id: 'cal-rc-007',
    comune: 'Palmi',
    localita: 'Tonnara e Scoglio dell\'Ulivo',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.3583,
    lon: 15.8500,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/palmi-tonnara',
    attiva: true,
  },
  {
    id: 'cal-rc-008',
    comune: 'Gioia Tauro',
    localita: 'Porto Commerciale',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.4261,
    lon: 15.8917,
    tipo: 'traffico',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gioia-tauro-porto',
    attiva: true,
  },
  {
    id: 'cal-rc-009',
    comune: 'Siderno',
    localita: 'Lungomare delle Palme',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2681,
    lon: 16.2972,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/siderno-lungomare',
    attiva: false,
  },
  {
    id: 'cal-rc-010',
    comune: 'Locri',
    localita: 'Spiaggia e Area Archeologica',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2361,
    lon: 16.2639,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/locri-area-archeologica',
    attiva: true,
  },
  {
    id: 'cal-rc-011',
    comune: 'Roccella Ionica',
    localita: 'Porto delle Grazie',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.3194,
    lon: 16.4083,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/roccella-ionica-porto',
    attiva: true,
  },
  {
    id: 'cal-rc-012',
    comune: 'Bova Marina',
    localita: 'Lido e Costa dei Gelsomini',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 37.9306,
    lon: 15.9194,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/bova-marina-lido',
    attiva: false,
  },
  {
    id: 'cal-rc-013',
    comune: 'Gerace',
    localita: 'Borgo Medievale',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2722,
    lon: 16.2194,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gerace-borgo',
    attiva: true,
  },
  {
    id: 'cal-rc-014',
    comune: 'Stilo',
    localita: 'Cattolica e Panorama',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.4778,
    lon: 16.4694,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/stilo-cattolica',
    attiva: false,
  },
  {
    id: 'cal-rc-015',
    comune: 'Gambarie',
    localita: 'Impianti Sci Aspromonte',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1667,
    lon: 15.8417,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/gambarie-impianti',
    attiva: true,
  },
  {
    id: 'cal-rc-016',
    comune: 'Gambarie',
    localita: 'Piazzale Mangeruca',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1681,
    lon: 15.8444,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gambarie-piazzale',
    attiva: true,
  },
  {
    id: 'cal-rc-017',
    comune: 'Melito di Porto Salvo',
    localita: 'Capo Sud e Spiaggia',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 37.9194,
    lon: 15.7833,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/melito-porto-salvo-spiaggia',
    attiva: false,
  },
  {
    id: 'cal-rc-018',
    comune: 'Reggio Calabria',
    localita: 'Aeroporto Tito Minniti',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.0722,
    lon: 15.6519,
    tipo: 'traffico',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/reggio-calabria-aeroporto',
    attiva: true,
  },

  // === LOMBARDIA ===
  {
    id: 'lom-bg-001',
    comune: 'Bergamo',
    localita: 'Città Alta',
    provincia: 'BG',
    regione: 'Lombardia',
    lat: 45.7050,
    lon: 9.6617,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/bergamo/citta-alta-bergamo.html',
    attiva: true,
  },
  {
    id: 'lom-bs-001',
    comune: 'Brescia',
    localita: 'Piazza della Loggia',
    provincia: 'BS',
    regione: 'Lombardia',
    lat: 45.5416,
    lon: 10.2118,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/brescia/piazza-loggia-brescia.html',
    attiva: true,
  },
  {
    id: 'lom-co-001',
    comune: 'Como',
    localita: 'Lago di Como',
    provincia: 'CO',
    regione: 'Lombardia',
    lat: 45.8081,
    lon: 9.0852,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/como/lago-como.html',
    attiva: true,
  },
  {
    id: 'lom-lc-001',
    comune: 'Lecco',
    localita: 'Lago di Lecco',
    provincia: 'LC',
    regione: 'Lombardia',
    lat: 45.8556,
    lon: 9.3967,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/lecco/lago-lecco.html',
    attiva: true,
  },
  {
    id: 'lom-mn-001',
    comune: 'Mantova',
    localita: 'Piazza Sordello',
    provincia: 'MN',
    regione: 'Lombardia',
    lat: 45.1564,
    lon: 10.7914,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lombardia/mantova/piazza-sordello.html',
    attiva: true,
  },
  {
    id: 'lom-pv-001',
    comune: 'Pavia',
    localita: 'Ponte Coperto',
    provincia: 'PV',
    regione: 'Lombardia',
    lat: 45.1847,
    lon: 9.1581,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/lombardia/pavia/ponte-coperto',
    attiva: true,
  },

  // === PIEMONTE ===
  {
    id: 'pie-at-001',
    comune: 'Asti',
    localita: 'Piazza Alfieri',
    provincia: 'AT',
    regione: 'Piemonte',
    lat: 44.9004,
    lon: 8.2064,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/asti/piazza-alfieri-asti.html',
    attiva: true,
  },
  {
    id: 'pie-cn-001',
    comune: 'Cuneo',
    localita: 'Piazza Galimberti',
    provincia: 'CN',
    regione: 'Piemonte',
    lat: 44.3845,
    lon: 7.5428,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/piemonte/cuneo/piazza-galimberti',
    attiva: true,
  },
  {
    id: 'pie-vb-001',
    comune: 'Verbania',
    localita: 'Lago Maggiore',
    provincia: 'VB',
    regione: 'Piemonte',
    lat: 45.9261,
    lon: 8.5522,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/verbano-cusio-ossola/lago-maggiore-verbania.html',
    attiva: true,
  },
  {
    id: 'pie-vb-002',
    comune: 'Stresa',
    localita: 'Lungolago Stresa',
    provincia: 'VB',
    regione: 'Piemonte',
    lat: 45.8836,
    lon: 8.5342,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/piemonte/verbano-cusio-ossola/stresa-lungolago.html',
    attiva: true,
  },

  // === VENETO ===
  {
    id: 'ven-vr-001',
    comune: 'Verona',
    localita: 'Arena di Verona',
    provincia: 'VR',
    regione: 'Veneto',
    lat: 45.4386,
    lon: 10.9942,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/verona/arena-verona.html',
    attiva: true,
  },
  {
    id: 'ven-pd-001',
    comune: 'Padova',
    localita: 'Piazza delle Erbe',
    provincia: 'PD',
    regione: 'Veneto',
    lat: 45.4075,
    lon: 11.8764,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/padova/piazza-erbe-padova.html',
    attiva: true,
  },
  {
    id: 'ven-vi-001',
    comune: 'Vicenza',
    localita: 'Piazza dei Signori',
    provincia: 'VI',
    regione: 'Veneto',
    lat: 45.5464,
    lon: 11.5475,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/veneto/vicenza/piazza-signori',
    attiva: true,
  },
  {
    id: 'ven-bl-001',
    comune: 'Cortina d\'Ampezzo',
    localita: 'Centro e Dolomiti',
    provincia: 'BL',
    regione: 'Veneto',
    lat: 46.5369,
    lon: 12.1356,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/belluno/cortina-ampezzo.html',
    attiva: true,
  },
  {
    id: 'ven-ve-004',
    comune: 'Jesolo',
    localita: 'Spiaggia Jesolo',
    provincia: 'VE',
    regione: 'Veneto',
    lat: 45.5078,
    lon: 12.6378,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/veneto/venezia/jesolo-spiaggia.html',
    attiva: true,
  },

  // === FRIULI VENEZIA GIULIA ===
  {
    id: 'fvg-ts-001',
    comune: 'Trieste',
    localita: 'Molo Audace',
    provincia: 'TS',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6464,
    lon: 13.7628,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/trieste/molo-audace-trieste.html',
    attiva: true,
  },
  {
    id: 'fvg-ts-002',
    comune: 'Trieste',
    localita: 'Piazza Unità d\'Italia',
    provincia: 'TS',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6492,
    lon: 13.7681,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/trieste/piazza-unita-trieste.html',
    attiva: true,
  },
  {
    id: 'fvg-ud-001',
    comune: 'Udine',
    localita: 'Piazza Libertà',
    provincia: 'UD',
    regione: 'Friuli Venezia Giulia',
    lat: 46.0636,
    lon: 13.2358,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/friuli-venezia-giulia/udine/piazza-liberta',
    attiva: true,
  },
  {
    id: 'fvg-go-001',
    comune: 'Grado',
    localita: 'Spiaggia Grado',
    provincia: 'GO',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6783,
    lon: 13.3911,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/gorizia/grado-spiaggia.html',
    attiva: true,
  },
  {
    id: 'fvg-ud-002',
    comune: 'Lignano Sabbiadoro',
    localita: 'Spiaggia Lignano',
    provincia: 'UD',
    regione: 'Friuli Venezia Giulia',
    lat: 45.6908,
    lon: 13.1353,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/friuli-venezia-giulia/udine/lignano-sabbiadoro.html',
    attiva: true,
  },

  // === TRENTINO ALTO ADIGE ===
  {
    id: 'taa-tn-001',
    comune: 'Trento',
    localita: 'Piazza Duomo',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 46.0679,
    lon: 11.1211,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/piazza-duomo-trento.html',
    attiva: true,
  },
  {
    id: 'taa-bz-001',
    comune: 'Bolzano',
    localita: 'Piazza Walther',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.4983,
    lon: 11.3548,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/piazza-walther-bolzano.html',
    attiva: true,
  },
  {
    id: 'taa-tn-002',
    comune: 'Madonna di Campiglio',
    localita: 'Piste da Sci',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 46.2322,
    lon: 10.8247,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/madonna-campiglio.html',
    attiva: true,
  },
  {
    id: 'taa-bz-002',
    comune: 'Ortisei',
    localita: 'Val Gardena',
    provincia: 'BZ',
    regione: 'Trentino Alto Adige',
    lat: 46.5758,
    lon: 11.6736,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/bolzano/val-gardena.html',
    attiva: true,
  },
  {
    id: 'taa-tn-003',
    comune: 'Canazei',
    localita: 'Dolomiti Fassa',
    provincia: 'TN',
    regione: 'Trentino Alto Adige',
    lat: 46.4764,
    lon: 11.7711,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/trentino-alto-adige/trento/canazei-dolomiti.html',
    attiva: true,
  },

  // === LIGURIA ===
  {
    id: 'lig-ge-001',
    comune: 'Genova',
    localita: 'Porto Antico',
    provincia: 'GE',
    regione: 'Liguria',
    lat: 44.4075,
    lon: 8.9278,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/genova/porto-antico-genova.html',
    attiva: true,
  },
  {
    id: 'lig-ge-002',
    comune: 'Portofino',
    localita: 'Porticciolo Portofino',
    provincia: 'GE',
    regione: 'Liguria',
    lat: 44.3033,
    lon: 9.2100,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/genova/portofino.html',
    attiva: true,
  },
  {
    id: 'lig-sp-001',
    comune: 'Riomaggiore',
    localita: 'Cinque Terre',
    provincia: 'SP',
    regione: 'Liguria',
    lat: 44.0997,
    lon: 9.7381,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/la-spezia/cinque-terre-riomaggiore.html',
    attiva: true,
  },
  {
    id: 'lig-im-001',
    comune: 'Sanremo',
    localita: 'Porto Vecchio',
    provincia: 'IM',
    regione: 'Liguria',
    lat: 43.8155,
    lon: 7.7764,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/imperia/sanremo-porto.html',
    attiva: true,
  },
  {
    id: 'lig-sv-001',
    comune: 'Alassio',
    localita: 'Spiaggia Alassio',
    provincia: 'SV',
    regione: 'Liguria',
    lat: 44.0083,
    lon: 8.1703,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/liguria/savona/alassio-spiaggia.html',
    attiva: true,
  },
  {
    id: 'lig-sp-002',
    comune: 'La Spezia',
    localita: 'Golfo della Spezia',
    provincia: 'SP',
    regione: 'Liguria',
    lat: 44.1025,
    lon: 9.8239,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/liguria/la-spezia/golfo-spezia',
    attiva: true,
  },

  // === EMILIA ROMAGNA ===
  {
    id: 'ero-bo-001',
    comune: 'Bologna',
    localita: 'Piazza Maggiore',
    provincia: 'BO',
    regione: 'Emilia Romagna',
    lat: 44.4939,
    lon: 11.3428,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/bologna/piazza-maggiore-bologna.html',
    attiva: true,
  },
  {
    id: 'ero-rn-001',
    comune: 'Rimini',
    localita: 'Spiaggia Rimini',
    provincia: 'RN',
    regione: 'Emilia Romagna',
    lat: 44.0678,
    lon: 12.5695,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/rimini/rimini-spiaggia.html',
    attiva: true,
  },
  {
    id: 'ero-rn-002',
    comune: 'Riccione',
    localita: 'Spiaggia Riccione',
    provincia: 'RN',
    regione: 'Emilia Romagna',
    lat: 44.0053,
    lon: 12.6583,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/rimini/riccione-spiaggia.html',
    attiva: true,
  },
  {
    id: 'ero-ra-001',
    comune: 'Ravenna',
    localita: 'Piazza del Popolo',
    provincia: 'RA',
    regione: 'Emilia Romagna',
    lat: 44.4175,
    lon: 12.2011,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/emilia-romagna/ravenna/piazza-popolo',
    attiva: true,
  },
  {
    id: 'ero-pr-001',
    comune: 'Parma',
    localita: 'Piazza Garibaldi',
    provincia: 'PR',
    regione: 'Emilia Romagna',
    lat: 44.8015,
    lon: 10.3278,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/parma/piazza-garibaldi-parma.html',
    attiva: true,
  },
  {
    id: 'ero-mo-001',
    comune: 'Modena',
    localita: 'Piazza Grande',
    provincia: 'MO',
    regione: 'Emilia Romagna',
    lat: 44.6458,
    lon: 10.9256,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/emilia-romagna/modena/piazza-grande',
    attiva: true,
  },
  {
    id: 'ero-fe-001',
    comune: 'Ferrara',
    localita: 'Piazza Trento e Trieste',
    provincia: 'FE',
    regione: 'Emilia Romagna',
    lat: 44.8353,
    lon: 11.6197,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/emilia-romagna/ferrara/piazza-trento-trieste',
    attiva: true,
  },
  {
    id: 'ero-fc-001',
    comune: 'Cesenatico',
    localita: 'Porto Canale',
    provincia: 'FC',
    regione: 'Emilia Romagna',
    lat: 44.2058,
    lon: 12.3950,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/emilia-romagna/forli-cesena/cesenatico-porto.html',
    attiva: true,
  },

  // === TOSCANA ===
  {
    id: 'tos-fi-003',
    comune: 'Firenze',
    localita: 'Piazza del Duomo',
    provincia: 'FI',
    regione: 'Toscana',
    lat: 43.7731,
    lon: 11.2560,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/firenze/duomo-firenze.html',
    attiva: true,
  },
  {
    id: 'tos-pi-001',
    comune: 'Pisa',
    localita: 'Torre di Pisa',
    provincia: 'PI',
    regione: 'Toscana',
    lat: 43.7228,
    lon: 10.3966,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/pisa/torre-pisa.html',
    attiva: true,
  },
  {
    id: 'tos-si-001',
    comune: 'Siena',
    localita: 'Piazza del Campo',
    provincia: 'SI',
    regione: 'Toscana',
    lat: 43.3186,
    lon: 11.3308,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/siena/piazza-del-campo-siena.html',
    attiva: true,
  },
  {
    id: 'tos-lu-001',
    comune: 'Lucca',
    localita: 'Piazza Anfiteatro',
    provincia: 'LU',
    regione: 'Toscana',
    lat: 43.8429,
    lon: 10.5022,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/toscana/lucca/piazza-anfiteatro',
    attiva: true,
  },
  {
    id: 'tos-li-001',
    comune: 'Livorno',
    localita: 'Porto di Livorno',
    provincia: 'LI',
    regione: 'Toscana',
    lat: 43.5506,
    lon: 10.3131,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/livorno/porto-livorno.html',
    attiva: true,
  },
  {
    id: 'tos-ar-001',
    comune: 'Arezzo',
    localita: 'Piazza Grande',
    provincia: 'AR',
    regione: 'Toscana',
    lat: 43.4636,
    lon: 11.8797,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/toscana/arezzo/piazza-grande',
    attiva: true,
  },
  {
    id: 'tos-lu-002',
    comune: 'Viareggio',
    localita: 'Passeggiata Viareggio',
    provincia: 'LU',
    regione: 'Toscana',
    lat: 43.8678,
    lon: 10.2486,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/lucca/viareggio-passeggiata.html',
    attiva: true,
  },
  {
    id: 'tos-lu-003',
    comune: 'Forte dei Marmi',
    localita: 'Spiaggia Forte dei Marmi',
    provincia: 'LU',
    regione: 'Toscana',
    lat: 43.9631,
    lon: 10.1683,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/lucca/forte-dei-marmi.html',
    attiva: true,
  },
  {
    id: 'tos-li-002',
    comune: 'Portoferraio',
    localita: 'Isola d\'Elba',
    provincia: 'LI',
    regione: 'Toscana',
    lat: 42.8139,
    lon: 10.3244,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/toscana/livorno/isola-elba-portoferraio.html',
    attiva: true,
  },

  // === LAZIO (aggiuntive) ===
  {
    id: 'laz-rm-006',
    comune: 'Roma',
    localita: 'Fori Imperiali',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.8935,
    lon: 12.4877,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/fori-imperiali-roma.html',
    attiva: true,
  },
  {
    id: 'laz-rm-007',
    comune: 'Roma',
    localita: 'Vaticano Piazza San Pietro',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.9022,
    lon: 12.4533,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/roma/piazza-san-pietro.html',
    attiva: true,
  },
  {
    id: 'laz-rm-008',
    comune: 'Ostia',
    localita: 'Spiaggia Ostia',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 41.7328,
    lon: 12.2781,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/lazio/roma/ostia-spiaggia',
    attiva: true,
  },
  {
    id: 'laz-rm-009',
    comune: 'Civitavecchia',
    localita: 'Porto Civitavecchia',
    provincia: 'RM',
    regione: 'Lazio',
    lat: 42.0931,
    lon: 11.7956,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/viterbo/civitavecchia-porto.html',
    attiva: true,
  },
  {
    id: 'laz-lt-001',
    comune: 'Gaeta',
    localita: 'Lungomare Gaeta',
    provincia: 'LT',
    regione: 'Lazio',
    lat: 41.2119,
    lon: 13.5717,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/lazio/latina/gaeta-spiaggia.html',
    attiva: true,
  },

  // === UMBRIA ===
  {
    id: 'umb-pg-001',
    comune: 'Perugia',
    localita: 'Piazza IV Novembre',
    provincia: 'PG',
    regione: 'Umbria',
    lat: 43.1122,
    lon: 12.3886,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/perugia/piazza-iv-novembre.html',
    attiva: true,
  },
  {
    id: 'umb-pg-002',
    comune: 'Assisi',
    localita: 'Basilica San Francesco',
    provincia: 'PG',
    regione: 'Umbria',
    lat: 43.0694,
    lon: 12.6139,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/perugia/assisi-basilica.html',
    attiva: true,
  },
  {
    id: 'umb-tr-001',
    comune: 'Orvieto',
    localita: 'Duomo di Orvieto',
    provincia: 'TR',
    regione: 'Umbria',
    lat: 42.7181,
    lon: 12.1139,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/umbria/terni/orvieto-duomo',
    attiva: true,
  },
  {
    id: 'umb-pg-003',
    comune: 'Spoleto',
    localita: 'Piazza del Duomo',
    provincia: 'PG',
    regione: 'Umbria',
    lat: 42.7347,
    lon: 12.7378,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/umbria/perugia/spoleto-duomo',
    attiva: true,
  },
  {
    id: 'umb-tr-002',
    comune: 'Terni',
    localita: 'Cascata delle Marmore',
    provincia: 'TR',
    regione: 'Umbria',
    lat: 42.5547,
    lon: 12.7050,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/umbria/terni/cascata-marmore.html',
    attiva: true,
  },

  // === MARCHE ===
  {
    id: 'mar-an-001',
    comune: 'Ancona',
    localita: 'Porto di Ancona',
    provincia: 'AN',
    regione: 'Marche',
    lat: 43.6158,
    lon: 13.5189,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/ancona/porto-ancona.html',
    attiva: true,
  },
  {
    id: 'mar-pu-001',
    comune: 'Pesaro',
    localita: 'Spiaggia Pesaro',
    provincia: 'PU',
    regione: 'Marche',
    lat: 43.9108,
    lon: 12.9139,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/pesaro-urbino/pesaro-spiaggia.html',
    attiva: true,
  },
  {
    id: 'mar-pu-002',
    comune: 'Urbino',
    localita: 'Palazzo Ducale',
    provincia: 'PU',
    regione: 'Marche',
    lat: 43.7261,
    lon: 12.6364,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/marche/pesaro-urbino/urbino-palazzo-ducale',
    attiva: true,
  },
  {
    id: 'mar-ap-001',
    comune: 'San Benedetto del Tronto',
    localita: 'Lungomare San Benedetto',
    provincia: 'AP',
    regione: 'Marche',
    lat: 42.9500,
    lon: 13.8833,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/ascoli-piceno/san-benedetto-tronto.html',
    attiva: true,
  },
  {
    id: 'mar-an-002',
    comune: 'Senigallia',
    localita: 'Spiaggia Senigallia',
    provincia: 'AN',
    regione: 'Marche',
    lat: 43.7156,
    lon: 13.2194,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/marche/ancona/senigallia-spiaggia.html',
    attiva: true,
  },

  // === ABRUZZO ===
  {
    id: 'abr-pe-001',
    comune: 'Pescara',
    localita: 'Lungomare Pescara',
    provincia: 'PE',
    regione: 'Abruzzo',
    lat: 42.4619,
    lon: 14.2147,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/pescara/lungomare-pescara.html',
    attiva: true,
  },
  {
    id: 'abr-aq-001',
    comune: 'L\'Aquila',
    localita: 'Piazza Duomo',
    provincia: 'AQ',
    regione: 'Abruzzo',
    lat: 42.3500,
    lon: 13.3997,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/abruzzo/l-aquila/piazza-duomo',
    attiva: true,
  },
  {
    id: 'abr-te-001',
    comune: 'Teramo',
    localita: 'Piazza Martiri',
    provincia: 'TE',
    regione: 'Abruzzo',
    lat: 42.6589,
    lon: 13.7042,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/abruzzo/teramo/piazza-martiri',
    attiva: true,
  },
  {
    id: 'abr-aq-002',
    comune: 'Roccaraso',
    localita: 'Piste Sci Roccaraso',
    provincia: 'AQ',
    regione: 'Abruzzo',
    lat: 41.8444,
    lon: 14.0778,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/abruzzo/l-aquila/roccaraso-neve.html',
    attiva: true,
  },
  {
    id: 'abr-aq-003',
    comune: 'Scanno',
    localita: 'Lago di Scanno',
    provincia: 'AQ',
    regione: 'Abruzzo',
    lat: 41.9025,
    lon: 13.8803,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://www.meteowebcam.it/webcam/abruzzo/scanno-lago',
    attiva: true,
  },

  // === CAMPANIA (aggiuntive) ===
  {
    id: 'cam-na-004',
    comune: 'Capri',
    localita: 'Faraglioni Capri',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.5509,
    lon: 14.2317,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/capri-faraglioni.html',
    attiva: true,
  },
  {
    id: 'cam-na-005',
    comune: 'Sorrento',
    localita: 'Porto di Sorrento',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.6263,
    lon: 14.3764,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/sorrento-porto.html',
    attiva: true,
  },
  {
    id: 'cam-sa-001',
    comune: 'Amalfi',
    localita: 'Costiera Amalfitana',
    provincia: 'SA',
    regione: 'Campania',
    lat: 40.6342,
    lon: 14.6027,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/salerno/amalfi-costiera.html',
    attiva: true,
  },
  {
    id: 'cam-sa-002',
    comune: 'Positano',
    localita: 'Spiaggia Grande Positano',
    provincia: 'SA',
    regione: 'Campania',
    lat: 40.6281,
    lon: 14.4839,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/salerno/positano-spiaggia.html',
    attiva: true,
  },
  {
    id: 'cam-sa-003',
    comune: 'Salerno',
    localita: 'Lungomare Salerno',
    provincia: 'SA',
    regione: 'Campania',
    lat: 40.6744,
    lon: 14.7611,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/salerno/lungomare-salerno.html',
    attiva: true,
  },
  {
    id: 'cam-na-006',
    comune: 'Ischia',
    localita: 'Porto Ischia',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.7333,
    lon: 13.9461,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/campania/napoli/ischia-porto.html',
    attiva: true,
  },
  {
    id: 'cam-na-007',
    comune: 'Procida',
    localita: 'Marina Corricella',
    provincia: 'NA',
    regione: 'Campania',
    lat: 40.7547,
    lon: 14.0172,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/campania/napoli/procida-corricella',
    attiva: true,
  },

  // === PUGLIA ===
  {
    id: 'pug-ba-001',
    comune: 'Bari',
    localita: 'Lungomare Imperatore Augusto',
    provincia: 'BA',
    regione: 'Puglia',
    lat: 41.1189,
    lon: 16.8680,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/bari/bari-lungomare.html',
    attiva: true,
  },
  {
    id: 'pug-le-001',
    comune: 'Lecce',
    localita: 'Piazza Sant\'Oronzo',
    provincia: 'LE',
    regione: 'Puglia',
    lat: 40.3536,
    lon: 18.1742,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/lecce/piazza-oronzo-lecce.html',
    attiva: true,
  },
  {
    id: 'pug-le-002',
    comune: 'Gallipoli',
    localita: 'Spiaggia Gallipoli',
    provincia: 'LE',
    regione: 'Puglia',
    lat: 40.0572,
    lon: 17.9931,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/lecce/gallipoli-spiaggia.html',
    attiva: true,
  },
  {
    id: 'pug-le-003',
    comune: 'Otranto',
    localita: 'Porto Otranto',
    provincia: 'LE',
    regione: 'Puglia',
    lat: 40.1469,
    lon: 18.4942,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/lecce/otranto-porto.html',
    attiva: true,
  },
  {
    id: 'pug-fg-001',
    comune: 'Vieste',
    localita: 'Gargano Vieste',
    provincia: 'FG',
    regione: 'Puglia',
    lat: 41.8817,
    lon: 16.1778,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/foggia/vieste-gargano.html',
    attiva: true,
  },
  {
    id: 'pug-ba-002',
    comune: 'Polignano a Mare',
    localita: 'Grotta Palazzese',
    provincia: 'BA',
    regione: 'Puglia',
    lat: 40.9953,
    lon: 17.2189,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/bari/polignano-a-mare.html',
    attiva: true,
  },
  {
    id: 'pug-bt-001',
    comune: 'Trani',
    localita: 'Cattedrale sul Mare',
    provincia: 'BT',
    regione: 'Puglia',
    lat: 41.2761,
    lon: 16.4150,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/puglia/barletta-andria-trani/trani-cattedrale.html',
    attiva: true,
  },
  {
    id: 'pug-ta-001',
    comune: 'Taranto',
    localita: 'Mar Grande Taranto',
    provincia: 'TA',
    regione: 'Puglia',
    lat: 40.4644,
    lon: 17.2478,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/puglia/taranto/mar-grande',
    attiva: true,
  },

  // === BASILICATA ===
  {
    id: 'bas-mt-001',
    comune: 'Matera',
    localita: 'Sassi di Matera',
    provincia: 'MT',
    regione: 'Basilicata',
    lat: 40.6664,
    lon: 16.6043,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/matera/sassi-matera.html',
    attiva: true,
  },
  {
    id: 'bas-pz-001',
    comune: 'Potenza',
    localita: 'Centro Storico Potenza',
    provincia: 'PZ',
    regione: 'Basilicata',
    lat: 40.6414,
    lon: 15.8056,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/basilicata/potenza/centro-storico',
    attiva: true,
  },
  {
    id: 'bas-pz-002',
    comune: 'Maratea',
    localita: 'Costa di Maratea',
    provincia: 'PZ',
    regione: 'Basilicata',
    lat: 39.9972,
    lon: 15.7278,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/basilicata/potenza/maratea-costa.html',
    attiva: true,
  },

  // === MOLISE ===
  {
    id: 'mol-cb-001',
    comune: 'Campobasso',
    localita: 'Piazza Vittorio Emanuele',
    provincia: 'CB',
    regione: 'Molise',
    lat: 41.5633,
    lon: 14.6561,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/molise/campobasso/piazza-vittorio-emanuele',
    attiva: true,
  },
  {
    id: 'mol-cb-002',
    comune: 'Termoli',
    localita: 'Borgo Antico Termoli',
    provincia: 'CB',
    regione: 'Molise',
    lat: 42.0006,
    lon: 14.9958,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/molise/campobasso/termoli-borgo.html',
    attiva: true,
  },

  // === SICILIA ===
  {
    id: 'sic-pa-001',
    comune: 'Palermo',
    localita: 'Piazza Pretoria',
    provincia: 'PA',
    regione: 'Sicilia',
    lat: 38.1157,
    lon: 13.3615,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/palermo/palermo-piazza-pretoria.html',
    attiva: true,
  },
  {
    id: 'sic-pa-002',
    comune: 'Palermo',
    localita: 'Porto di Palermo',
    provincia: 'PA',
    regione: 'Sicilia',
    lat: 38.1200,
    lon: 13.3700,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/palermo/porto-palermo.html',
    attiva: true,
  },
  {
    id: 'sic-ct-001',
    comune: 'Catania',
    localita: 'Piazza del Duomo',
    provincia: 'CT',
    regione: 'Sicilia',
    lat: 37.5023,
    lon: 15.0872,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/catania/piazza-duomo-catania.html',
    attiva: true,
  },
  {
    id: 'sic-me-001',
    comune: 'Taormina',
    localita: 'Teatro Greco e Etna',
    provincia: 'ME',
    regione: 'Sicilia',
    lat: 37.8519,
    lon: 15.2922,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/messina/taormina-etna.html',
    attiva: true,
  },
  {
    id: 'sic-sr-001',
    comune: 'Siracusa',
    localita: 'Ortigia',
    provincia: 'SR',
    regione: 'Sicilia',
    lat: 37.0659,
    lon: 15.2937,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/siracusa/ortigia-siracusa.html',
    attiva: true,
  },
  {
    id: 'sic-pa-003',
    comune: 'Cefalù',
    localita: 'Spiaggia Cefalù',
    provincia: 'PA',
    regione: 'Sicilia',
    lat: 38.0394,
    lon: 14.0219,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/palermo/cefalu-spiaggia.html',
    attiva: true,
  },
  {
    id: 'sic-tp-001',
    comune: 'Trapani',
    localita: 'Porto Trapani',
    provincia: 'TP',
    regione: 'Sicilia',
    lat: 38.0176,
    lon: 12.5148,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/trapani/porto-trapani.html',
    attiva: true,
  },
  {
    id: 'sic-tp-002',
    comune: 'Marsala',
    localita: 'Porto Marsala',
    provincia: 'TP',
    regione: 'Sicilia',
    lat: 37.7983,
    lon: 12.4369,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/sicilia/trapani/marsala-porto',
    attiva: true,
  },
  {
    id: 'sic-ag-001',
    comune: 'Agrigento',
    localita: 'Valle dei Templi',
    provincia: 'AG',
    regione: 'Sicilia',
    lat: 37.2908,
    lon: 13.5886,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/agrigento/valle-dei-templi.html',
    attiva: true,
  },
  {
    id: 'sic-me-002',
    comune: 'Stromboli',
    localita: 'Vulcano Stromboli',
    provincia: 'ME',
    regione: 'Sicilia',
    lat: 38.7931,
    lon: 15.2131,
    tipo: 'vulcano',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/messina/stromboli-vulcano.html',
    attiva: true,
  },
  {
    id: 'sic-me-003',
    comune: 'Lipari',
    localita: 'Isole Eolie',
    provincia: 'ME',
    regione: 'Sicilia',
    lat: 38.4678,
    lon: 14.9556,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sicilia/messina/lipari-eolie.html',
    attiva: true,
  },

  // === SARDEGNA ===
  {
    id: 'sar-ca-001',
    comune: 'Cagliari',
    localita: 'Castello Cagliari',
    provincia: 'CA',
    regione: 'Sardegna',
    lat: 39.2238,
    lon: 9.1217,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/cagliari/castello-cagliari.html',
    attiva: true,
  },
  {
    id: 'sar-ca-002',
    comune: 'Cagliari',
    localita: 'Spiaggia Poetto',
    provincia: 'CA',
    regione: 'Sardegna',
    lat: 39.2003,
    lon: 9.1500,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/cagliari/poetto-spiaggia.html',
    attiva: true,
  },
  {
    id: 'sar-ss-001',
    comune: 'Alghero',
    localita: 'Centro Storico Alghero',
    provincia: 'SS',
    regione: 'Sardegna',
    lat: 40.5597,
    lon: 8.3197,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/sassari/alghero-centro.html',
    attiva: true,
  },
  {
    id: 'sar-ot-001',
    comune: 'Olbia',
    localita: 'Porto Olbia',
    provincia: 'OT',
    regione: 'Sardegna',
    lat: 40.9236,
    lon: 9.5028,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/olbia-tempio/olbia-porto.html',
    attiva: true,
  },
  {
    id: 'sar-ot-002',
    comune: 'Porto Cervo',
    localita: 'Costa Smeralda',
    provincia: 'OT',
    regione: 'Sardegna',
    lat: 41.1389,
    lon: 9.5389,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/olbia-tempio/costa-smeralda.html',
    attiva: true,
  },
  {
    id: 'sar-ss-002',
    comune: 'Stintino',
    localita: 'Spiaggia La Pelosa',
    provincia: 'SS',
    regione: 'Sardegna',
    lat: 40.9378,
    lon: 8.2261,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/sassari/stintino-pelosa.html',
    attiva: true,
  },
  {
    id: 'sar-ot-003',
    comune: 'La Maddalena',
    localita: 'Arcipelago Maddalena',
    provincia: 'OT',
    regione: 'Sardegna',
    lat: 41.2139,
    lon: 9.4058,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/olbia-tempio/la-maddalena.html',
    attiva: true,
  },
  {
    id: 'sar-ca-003',
    comune: 'Villasimius',
    localita: 'Capo Carbonara',
    provincia: 'CA',
    regione: 'Sardegna',
    lat: 39.1356,
    lon: 9.5103,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/sardegna/cagliari/villasimius-capo-carbonara.html',
    attiva: true,
  },
  {
    id: 'sar-or-001',
    comune: 'Bosa',
    localita: 'Castello di Serravalle',
    provincia: 'OR',
    regione: 'Sardegna',
    lat: 40.2981,
    lon: 8.4958,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://www.webcamitalia.it/webcam/sardegna/oristano/bosa-castello',
    attiva: true,
  },

  // === VALLE D'AOSTA ===
  {
    id: 'vda-ao-001',
    comune: 'Aosta',
    localita: 'Centro Storico Aosta',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.7372,
    lon: 7.3197,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-d-aosta/aosta/centro-storico-aosta.html',
    attiva: true,
  },
  {
    id: 'vda-ao-002',
    comune: 'Courmayeur',
    localita: 'Monte Bianco',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.7964,
    lon: 6.9706,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-d-aosta/aosta/courmayeur-monte-bianco.html',
    attiva: true,
  },
  {
    id: 'vda-ao-003',
    comune: 'Cervinia',
    localita: 'Cervino Matterhorn',
    provincia: 'AO',
    regione: 'Valle d\'Aosta',
    lat: 45.9356,
    lon: 7.6458,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://www.skylinewebcams.com/it/webcam/italia/valle-d-aosta/aosta/cervinia-cervino.html',
    attiva: true,
  },
];
