export interface TerritorialWebcam {
  id: string;
  comune: string;
  localita: string;
  provincia: string;
  regione: string;
  lat: number;
  lon: number;
  tipo: 'panoramica' | 'mare' | 'montagna' | 'citta' | 'traffico' | 'vulcano';
  portale: string;
  url: string;
  attiva: boolean;
}

export const WEBCAMS_ITALIA: TerritorialWebcam[] = [
  // === CALABRIA - Provincia di Cosenza ===
  {
    id: 'cal-cs-001',
    comune: 'Cosenza',
    localita: 'Centro Storico',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3009,
    lon: 16.2539,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/cosenza-centro-storico',
    attiva: true,
  },
  {
    id: 'cal-cs-002',
    comune: 'Cosenza',
    localita: 'Ponte Calatrava',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.2975,
    lon: 16.2520,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/cosenza-ponte-calatrava',
    attiva: true,
  },
  {
    id: 'cal-cs-003',
    comune: 'Rende',
    localita: 'Università della Calabria',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3566,
    lon: 16.2260,
    tipo: 'citta',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/rende-universita',
    attiva: true,
  },
  {
    id: 'cal-cs-004',
    comune: 'Scalea',
    localita: 'Lungomare',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8134,
    lon: 15.7917,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/scalea-lungomare',
    attiva: true,
  },
  {
    id: 'cal-cs-005',
    comune: 'Diamante',
    localita: 'Spiaggia e Isola di Cirella',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.6764,
    lon: 15.8197,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/diamante-cirella',
    attiva: true,
  },
  {
    id: 'cal-cs-006',
    comune: 'Praia a Mare',
    localita: 'Isola di Dino',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8950,
    lon: 15.7739,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/praia-a-mare-isola-dino',
    attiva: true,
  },
  {
    id: 'cal-cs-007',
    comune: 'Cetraro',
    localita: 'Porto',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.5167,
    lon: 15.9375,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/cetraro-porto',
    attiva: true,
  },
  {
    id: 'cal-cs-008',
    comune: 'Paola',
    localita: 'Santuario San Francesco',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3608,
    lon: 16.0394,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/paola-santuario',
    attiva: true,
  },
  {
    id: 'cal-cs-009',
    comune: 'Amantea',
    localita: 'Spiaggia',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.1356,
    lon: 16.0717,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/amantea-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-cs-010',
    comune: 'Belvedere Marittimo',
    localita: 'Centro e Mare',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.6167,
    lon: 15.8597,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/belvedere-marittimo',
    attiva: true,
  },
  {
    id: 'cal-cs-011',
    comune: 'Castrovillari',
    localita: 'Piazza Municipio',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8121,
    lon: 16.2028,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/castrovillari-centro',
    attiva: true,
  },
  {
    id: 'cal-cs-012',
    comune: 'Morano Calabro',
    localita: 'Borgo e Pollino',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8419,
    lon: 16.1381,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/morano-calabro-pollino',
    attiva: true,
  },
  {
    id: 'cal-cs-013',
    comune: 'San Giovanni in Fiore',
    localita: 'Abbazia Florense',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.2583,
    lon: 16.6972,
    tipo: 'montagna',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/san-giovanni-in-fiore',
    attiva: true,
  },
  {
    id: 'cal-cs-014',
    comune: 'Camigliatello Silano',
    localita: 'Lago Cecita',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3333,
    lon: 16.5250,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/camigliatello-lago-cecita',
    attiva: true,
  },
  {
    id: 'cal-cs-015',
    comune: 'Camigliatello Silano',
    localita: 'Impianti Sci Monte Curcio',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.3167,
    lon: 16.5083,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/camigliatello-monte-curcio',
    attiva: false,
  },
  {
    id: 'cal-cs-016',
    comune: 'Lorica',
    localita: 'Lago Arvo',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.2833,
    lon: 16.5167,
    tipo: 'montagna',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/lorica-lago-arvo',
    attiva: true,
  },
  {
    id: 'cal-cs-017',
    comune: 'Longobucco',
    localita: 'Panorama Sila',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.4464,
    lon: 16.6108,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/longobucco-sila',
    attiva: true,
  },
  {
    id: 'cal-cs-018',
    comune: 'Rossano',
    localita: 'Lungomare Lido Sant\'Angelo',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.5764,
    lon: 16.6367,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/rossano-lido',
    attiva: true,
  },
  {
    id: 'cal-cs-019',
    comune: 'Corigliano Calabro',
    localita: 'Porto e Castello',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.5972,
    lon: 16.5186,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/corigliano-calabro-porto',
    attiva: true,
  },
  {
    id: 'cal-cs-020',
    comune: 'Trebisacce',
    localita: 'Lungomare',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8675,
    lon: 16.5353,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/trebisacce-lungomare',
    attiva: true,
  },
  {
    id: 'cal-cs-021',
    comune: 'Scalea',
    localita: 'Torre Talao',
    provincia: 'CS',
    regione: 'Calabria',
    lat: 39.8100,
    lon: 15.7889,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/scalea-torre-talao',
    attiva: false,
  },

  // === CALABRIA - Provincia di Catanzaro ===
  {
    id: 'cal-cz-001',
    comune: 'Catanzaro',
    localita: 'Piazza Prefettura',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9098,
    lon: 16.5879,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/catanzaro-piazza-prefettura',
    attiva: true,
  },
  {
    id: 'cal-cz-002',
    comune: 'Catanzaro',
    localita: 'Ponte Bisantis',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.8992,
    lon: 16.5750,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/catanzaro-ponte-bisantis',
    attiva: true,
  },
  {
    id: 'cal-cz-003',
    comune: 'Catanzaro Lido',
    localita: 'Lungomare',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.8333,
    lon: 16.6028,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/catanzaro-lido-lungomare',
    attiva: true,
  },
  {
    id: 'cal-cz-004',
    comune: 'Lamezia Terme',
    localita: 'Centro Città',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9683,
    lon: 16.3089,
    tipo: 'citta',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/lamezia-terme-centro',
    attiva: true,
  },
  {
    id: 'cal-cz-005',
    comune: 'Lamezia Terme',
    localita: 'Aeroporto Internazionale',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9058,
    lon: 16.2425,
    tipo: 'traffico',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/lamezia-aeroporto',
    attiva: true,
  },
  {
    id: 'cal-cz-006',
    comune: 'Soverato',
    localita: 'Spiaggia e Lungomare',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.6872,
    lon: 16.5489,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/soverato-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-cz-007',
    comune: 'Soverato',
    localita: 'Porto',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.6908,
    lon: 16.5517,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/soverato-porto',
    attiva: false,
  },
  {
    id: 'cal-cz-008',
    comune: 'Squillace',
    localita: 'Borgo e Golfo',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.7833,
    lon: 16.5194,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/squillace-golfo',
    attiva: true,
  },
  {
    id: 'cal-cz-009',
    comune: 'Taverna',
    localita: 'Centro Storico',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 39.0183,
    lon: 16.5833,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/taverna-centro',
    attiva: true,
  },
  {
    id: 'cal-cz-010',
    comune: 'Tiriolo',
    localita: 'Panorama Istmo',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9417,
    lon: 16.5111,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/tiriolo-panorama',
    attiva: true,
  },
  {
    id: 'cal-cz-011',
    comune: 'Sellia Marina',
    localita: 'Lido',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9056,
    lon: 16.7403,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/sellia-marina-lido',
    attiva: true,
  },
  {
    id: 'cal-cz-012',
    comune: 'Cropani',
    localita: 'Cropani Marina',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9408,
    lon: 16.7778,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/cropani-marina',
    attiva: true,
  },
  {
    id: 'cal-cz-013',
    comune: 'Botricello',
    localita: 'Spiaggia',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9361,
    lon: 16.8556,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/botricello-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-cz-014',
    comune: 'Catanzaro',
    localita: 'Parco della Biodiversità',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9042,
    lon: 16.5944,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/catanzaro-parco-biodiversita',
    attiva: true,
  },
  {
    id: 'cal-cz-015',
    comune: 'Lamezia Terme',
    localita: 'Stazione Centrale',
    provincia: 'CZ',
    regione: 'Calabria',
    lat: 38.9639,
    lon: 16.3125,
    tipo: 'traffico',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/lamezia-stazione',
    attiva: false,
  },

  // === CALABRIA - Provincia di Vibo Valentia ===
  {
    id: 'cal-vv-001',
    comune: 'Tropea',
    localita: 'Spiaggia e Santa Maria dell\'Isola',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6769,
    lon: 15.8978,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/tropea-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-vv-002',
    comune: 'Tropea',
    localita: 'Centro Storico e Affaccio',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6792,
    lon: 15.8953,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/tropea-centro-storico',
    attiva: true,
  },
  {
    id: 'cal-vv-003',
    comune: 'Pizzo Calabro',
    localita: 'Castello Murat e Mare',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7297,
    lon: 16.1597,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/pizzo-calabro-castello',
    attiva: true,
  },
  {
    id: 'cal-vv-004',
    comune: 'Pizzo Calabro',
    localita: 'Marina e Porto',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7264,
    lon: 16.1583,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/pizzo-calabro-marina',
    attiva: true,
  },
  {
    id: 'cal-vv-005',
    comune: 'Vibo Marina',
    localita: 'Porto Commerciale',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7083,
    lon: 16.1167,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/vibo-marina-porto',
    attiva: true,
  },
  {
    id: 'cal-vv-006',
    comune: 'Capo Vaticano',
    localita: 'Faro e Costa',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6167,
    lon: 15.8333,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/capo-vaticano-faro',
    attiva: true,
  },
  {
    id: 'cal-vv-007',
    comune: 'Zambrone',
    localita: 'Spiaggia Paradiso del Sub',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6972,
    lon: 15.9861,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/zambrone-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-vv-008',
    comune: 'Briatico',
    localita: 'Lido e Torre',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7306,
    lon: 16.0306,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/briatico-lido',
    attiva: true,
  },
  {
    id: 'cal-vv-009',
    comune: 'Ricadi',
    localita: 'Santa Domenica',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.6250,
    lon: 15.8583,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/ricadi-santa-domenica',
    attiva: true,
  },
  {
    id: 'cal-vv-010',
    comune: 'Serra San Bruno',
    localita: 'Certosa',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.5750,
    lon: 16.3264,
    tipo: 'montagna',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/serra-san-bruno-certosa',
    attiva: true,
  },
  {
    id: 'cal-vv-011',
    comune: 'Filadelfia',
    localita: 'Centro e Panorama',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.7167,
    lon: 16.2917,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/filadelfia-panorama',
    attiva: false,
  },
  {
    id: 'cal-vv-012',
    comune: 'Joppolo',
    localita: 'Costa e Coccorino',
    provincia: 'VV',
    regione: 'Calabria',
    lat: 38.5861,
    lon: 15.8972,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/joppolo-coccorino',
    attiva: true,
  },

  // === CALABRIA - Provincia di Crotone ===
  {
    id: 'cal-kr-001',
    comune: 'Crotone',
    localita: 'Lungomare e Castello',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0833,
    lon: 17.1236,
    tipo: 'citta',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/crotone-lungomare',
    attiva: true,
  },
  {
    id: 'cal-kr-002',
    comune: 'Crotone',
    localita: 'Porto Vecchio',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0806,
    lon: 17.1278,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/crotone-porto-vecchio',
    attiva: true,
  },
  {
    id: 'cal-kr-003',
    comune: 'Isola di Capo Rizzuto',
    localita: 'Area Marina Protetta',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 38.9583,
    lon: 17.0917,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/isola-capo-rizzuto-marina',
    attiva: true,
  },
  {
    id: 'cal-kr-004',
    comune: 'Le Castella',
    localita: 'Fortezza Aragonese',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 38.9083,
    lon: 17.0222,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/le-castella-fortezza',
    attiva: true,
  },
  {
    id: 'cal-kr-005',
    comune: 'Cirò Marina',
    localita: 'Porto e Spiaggia',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.3708,
    lon: 17.1250,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/ciro-marina-porto',
    attiva: true,
  },
  {
    id: 'cal-kr-006',
    comune: 'Cirò Marina',
    localita: 'Punta Alice',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.3833,
    lon: 17.1500,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/ciro-marina-punta-alice',
    attiva: false,
  },
  {
    id: 'cal-kr-007',
    comune: 'Melissa',
    localita: 'Torre Melissa Lido',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.3167,
    lon: 17.0750,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/melissa-lido',
    attiva: true,
  },
  {
    id: 'cal-kr-008',
    comune: 'Strongoli',
    localita: 'Strongoli Marina',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.2667,
    lon: 17.0500,
    tipo: 'mare',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/strongoli-marina',
    attiva: true,
  },
  {
    id: 'cal-kr-009',
    comune: 'Cutro',
    localita: 'Steccato di Cutro Spiaggia',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 38.9917,
    lon: 17.0167,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/cutro-steccato-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-kr-010',
    comune: 'Mesoraca',
    localita: 'Panorama Marchesato',
    provincia: 'KR',
    regione: 'Calabria',
    lat: 39.0778,
    lon: 16.7889,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/mesoraca-panorama',
    attiva: true,
  },

  // === CALABRIA - Provincia di Reggio Calabria ===
  {
    id: 'cal-rc-001',
    comune: 'Reggio Calabria',
    localita: 'Lungomare Falcomatà',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1114,
    lon: 15.6472,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/reggio-calabria-lungomare',
    attiva: true,
  },
  {
    id: 'cal-rc-002',
    comune: 'Reggio Calabria',
    localita: 'Stretto di Messina',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1097,
    lon: 15.6500,
    tipo: 'panoramica',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/reggio-calabria-stretto',
    attiva: true,
  },
  {
    id: 'cal-rc-003',
    comune: 'Reggio Calabria',
    localita: 'Piazza Duomo',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1100,
    lon: 15.6433,
    tipo: 'citta',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/reggio-calabria-piazza-duomo',
    attiva: true,
  },
  {
    id: 'cal-rc-004',
    comune: 'Scilla',
    localita: 'Spiaggia di Chianalea',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2528,
    lon: 15.7139,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/scilla-chianalea',
    attiva: true,
  },
  {
    id: 'cal-rc-005',
    comune: 'Scilla',
    localita: 'Castello Ruffo e Stretto',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2536,
    lon: 15.7167,
    tipo: 'panoramica',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/scilla-castello-ruffo',
    attiva: true,
  },
  {
    id: 'cal-rc-006',
    comune: 'Bagnara Calabra',
    localita: 'Marina e Costa Viola',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2833,
    lon: 15.8083,
    tipo: 'mare',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/bagnara-calabra-marina',
    attiva: true,
  },
  {
    id: 'cal-rc-007',
    comune: 'Palmi',
    localita: 'Tonnara e Scoglio dell\'Ulivo',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.3583,
    lon: 15.8500,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/palmi-tonnara',
    attiva: true,
  },
  {
    id: 'cal-rc-008',
    comune: 'Gioia Tauro',
    localita: 'Porto Commerciale',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.4261,
    lon: 15.8917,
    tipo: 'traffico',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gioia-tauro-porto',
    attiva: true,
  },
  {
    id: 'cal-rc-009',
    comune: 'Siderno',
    localita: 'Lungomare delle Palme',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2681,
    lon: 16.2972,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/siderno-lungomare',
    attiva: true,
  },
  {
    id: 'cal-rc-010',
    comune: 'Locri',
    localita: 'Spiaggia e Area Archeologica',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2361,
    lon: 16.2639,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/locri-area-archeologica',
    attiva: true,
  },
  {
    id: 'cal-rc-011',
    comune: 'Roccella Ionica',
    localita: 'Porto delle Grazie',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.3194,
    lon: 16.4083,
    tipo: 'mare',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/roccella-ionica-porto',
    attiva: true,
  },
  {
    id: 'cal-rc-012',
    comune: 'Bova Marina',
    localita: 'Lido e Costa dei Gelsomini',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 37.9306,
    lon: 15.9194,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/bova-marina-lido',
    attiva: true,
  },
  {
    id: 'cal-rc-013',
    comune: 'Gerace',
    localita: 'Borgo Medievale',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.2722,
    lon: 16.2194,
    tipo: 'panoramica',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gerace-borgo',
    attiva: true,
  },
  {
    id: 'cal-rc-014',
    comune: 'Stilo',
    localita: 'Cattolica e Panorama',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.4778,
    lon: 16.4694,
    tipo: 'panoramica',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/stilo-cattolica',
    attiva: false,
  },
  {
    id: 'cal-rc-015',
    comune: 'Gambarie',
    localita: 'Impianti Sci Aspromonte',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1667,
    lon: 15.8417,
    tipo: 'montagna',
    portale: 'skylinewebcams.com',
    url: 'https://skylinewebcams.com/webcam/calabria/gambarie-impianti',
    attiva: true,
  },
  {
    id: 'cal-rc-016',
    comune: 'Gambarie',
    localita: 'Piazzale Mangeruca',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.1681,
    lon: 15.8444,
    tipo: 'montagna',
    portale: 'meteowebcam.it',
    url: 'https://meteowebcam.it/webcam/calabria/gambarie-piazzale',
    attiva: true,
  },
  {
    id: 'cal-rc-017',
    comune: 'Melito di Porto Salvo',
    localita: 'Capo Sud e Spiaggia',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 37.9194,
    lon: 15.7833,
    tipo: 'mare',
    portale: 'calabriawebcam.it',
    url: 'https://calabriawebcam.it/webcam/calabria/melito-porto-salvo-spiaggia',
    attiva: true,
  },
  {
    id: 'cal-rc-018',
    comune: 'Reggio Calabria',
    localita: 'Aeroporto Tito Minniti',
    provincia: 'RC',
    regione: 'Calabria',
    lat: 38.0722,
    lon: 15.6519,
    tipo: 'traffico',
    portale: 'webcamitalia.it',
    url: 'https://webcamitalia.it/webcam/calabria/reggio-calabria-aeroporto',
    attiva: true,
  },
];
